---
kind: pipeline
type: docker
name: default

services:
  - name: postgresql
    image: postgres:12.1
    environment:
      POSTGRES_USER: claircore
      POSTGRES_DB: claircore

steps:
  - name: unit-and-integration
    image: golang:1.13.0
    environment:
      POSTGRES_CONNECTION_STRING: host=postgresql port=5432 user=claircore dbname=claircore sslmode=disable
    commands:
      - sleep 5
      - make integration

