// Code generated by "stringer -type=PackageKind -linecomment"; DO NOT EDIT.

package claircore

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[packageUnknown-0]
	_ = x[PackageBinary-1]
	_ = x[PackageSource-2]
	_ = x[PackageLayer-3]
	_ = x[PackageAncestry-4]
}

const _PackageKind_name = "binarysourcelayerancestry"

var _PackageKind_index = [...]uint8{0, 0, 6, 12, 17, 25}

func (i PackageKind) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_PackageKind_index)-1 {
		return "PackageKind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _PackageKind_name[_PackageKind_index[idx]:_PackageKind_index[idx+1]]
}
