// Cpedict is a command to generate a "TestDictionary" harness from the official
// CPE Dictionary.
package main

import (
	"archive/zip"
	"compress/gzip"
	"context"
	"encoding/json"
	"flag"
	"fmt"
	"io"
	"log/slog"
	"net/http"
	"os"
	"os/signal"
	"path"
	"strconv"
	"strings"
)

func main() {
	var code int
	defer func() {
		if code != 0 {
			os.Exit(code)
		}
	}()
	var level slog.LevelVar
	slog.SetDefault(slog.New(slog.NewTextHandler(os.Stderr, &slog.HandlerOptions{
		Level: &level,
	})))
	outfile := flag.String("o", "testdata/dictionary.list.gz", "output file")
	dictURL := flag.String("url", `https://nvd.nist.gov/feeds/json/cpe/2.0/nvdcpe-2.0.zip`, "dictionary url (JSON zip file format)")
	flag.BoolFunc("D", "debug output", func(value string) error {
		ok, err := strconv.ParseBool(value)
		if err != nil {
			return err
		}
		if ok {
			level.Set(slog.LevelDebug)
		}
		return nil
	})
	flag.Parse()
	ctx := context.Background()
	ctx, done := signal.NotifyContext(ctx, os.Interrupt)
	defer done()

	out, err := os.Create(*outfile)
	if err != nil {
		slog.Error("unable to open out file", "error", err)
		code = 1
		return
	}
	defer out.Close()

	if err := Main(ctx, out, *dictURL); err != nil {
		slog.Error("error processing CPE dictionary", "error", err)
		code = 1
		return
	}
}

func Main(ctx context.Context, out *os.File, dictURL string) error {
	z, err := fetchDict(ctx, dictURL)
	if err != nil {
		return err
	}

	outGz, err := gzip.NewWriterLevel(out, gzip.BestCompression)
	if err != nil {
		return err
	}
	defer outGz.Close()
	if _, err := io.WriteString(outGz, dictionaryHeader); err != nil {
		return err
	}

	for _, f := range z.File {
		if strings.HasSuffix(f.Name, "/") {
			continue
		}
		if err := processFile(ctx, outGz, f); err != nil {
			return err
		}
	}
	return nil
}

const dictionaryHeader = `# This file is a list of newline delimited 2.3 CPE names.
# Lines beginning with a "#" are comments, and blank lines are ignored.
#
# This file is autogenerated by "go tool cpedict".
`

func fetchDict(ctx context.Context, dictURL string) (*zip.Reader, error) {
	spool, err := os.CreateTemp("", path.Base(dictURL)+".")
	if err != nil {
		return nil, err
	}
	if err := os.Remove(spool.Name()); err != nil {
		return nil, err
	}
	slog.DebugContext(ctx, "using spool file", "path", spool.Name())

	req, err := http.NewRequestWithContext(ctx, http.MethodGet, dictURL, nil)
	if err != nil {
		return nil, err
	}

	slog.DebugContext(ctx, "fetch begin", "url", dictURL)
	res, err := http.DefaultClient.Do(req)
	if err != nil {
		return nil, err
	}
	defer res.Body.Close()
	switch res.StatusCode {
	case http.StatusOK:
	default:
		return nil, fmt.Errorf("unexpected response: %s", res.Status)
	}
	sz, err := io.Copy(spool, res.Body)
	if err != nil {
		return nil, err
	}
	slog.DebugContext(ctx, "fetch done", "url", dictURL)

	return zip.NewReader(spool, sz)
}

func processFile(ctx context.Context, out io.Writer, zf *zip.File) error {
	slog.DebugContext(ctx, "file begin", "file", zf.Name)
	f, err := zf.Open()
	if err != nil {
		return err
	}
	defer f.Close()

	var page cpeAPI
	dec := json.NewDecoder(f)
	if err := dec.Decode(&page); err != nil {
		return err
	}

	var wrote, skipped int
	for n, w := range page.Products {
		cpe := &w.CPE
		if cpe.Deprecated {
			skipped++
			continue
		}
		if _, err := io.WriteString(out, cpe.Name); err != nil {
			return err
		}
		if _, err := io.WriteString(out, "\n"); err != nil {
			return err
		}
		wrote++

		if n%100 == 0 {
			if err := ctx.Err(); err != nil {
				return err
			}
		}
	}
	slog.DebugContext(ctx, "file done", "file", zf.Name, "wrote", wrote, "skipped", skipped)

	return nil
}

type cpeAPI struct {
	Products []productCPE `json:"products"`
}

type productCPE struct {
	CPE cpe `json:"cpe"`
}

type cpe struct {
	Deprecated bool   `json:"deprecated"`
	Name       string `json:"cpeName"`
}
