// Code generated by internal/cmd/querymetadata. DO NOT EDIT.

package postgres

var queryMetadata = struct {
	Table map[string]string
	Op    map[string]string
}{
	Table: map[string]string{},
	Op: map[string]string{},
}
