#!/bin/sh
set -e

for cmd in ragel-go gofmt sed; do
	if ! command -v "$cmd" >/dev/null 2>&1; then
		printf 'missing needed command: %s\n' "$cmd" >&2
		exit 99
	fi
done

ragel-go -s -p -F1 -o _parser.go parser.rl
trap 'rm _parser.go' EXIT
{
	printf '// Code generated by ragel-go DO NOT EDIT.\n\n'
	gofmt -s _parser.go
} > parser.go
