// Code generated by ragel-go DO NOT EDIT.
package urn

import "errors"
import "fmt"

var urn_start  int  = 1
var _ = urn_start 
var urn_first_final  int  = 81
var _ = urn_first_final 
var urn_error  int  = 0
var _ = urn_error 
var urn_en_main  int  = 1
var _ = urn_en_main 
func parse(out *URN, data string) (err error) {
	var p, b, cs int
	pe := len(data)
	eof := len(data)
	pct := false
	
	{cs = int(urn_start);
	}
	{if p == pe  {
			goto _test_eof;
			
		}
		switch cs  {
			case 1:
			goto st_case_1;
			case 0:
			goto st_case_0;
			case 2:
			goto st_case_2;
			case 3:
			goto st_case_3;
			case 4:
			goto st_case_4;
			case 5:
			goto st_case_5;
			case 6:
			goto st_case_6;
			case 7:
			goto st_case_7;
			case 8:
			goto st_case_8;
			case 9:
			goto st_case_9;
			case 10:
			goto st_case_10;
			case 11:
			goto st_case_11;
			case 12:
			goto st_case_12;
			case 13:
			goto st_case_13;
			case 14:
			goto st_case_14;
			case 15:
			goto st_case_15;
			case 16:
			goto st_case_16;
			case 17:
			goto st_case_17;
			case 18:
			goto st_case_18;
			case 19:
			goto st_case_19;
			case 20:
			goto st_case_20;
			case 21:
			goto st_case_21;
			case 22:
			goto st_case_22;
			case 23:
			goto st_case_23;
			case 24:
			goto st_case_24;
			case 25:
			goto st_case_25;
			case 26:
			goto st_case_26;
			case 27:
			goto st_case_27;
			case 28:
			goto st_case_28;
			case 29:
			goto st_case_29;
			case 30:
			goto st_case_30;
			case 31:
			goto st_case_31;
			case 32:
			goto st_case_32;
			case 33:
			goto st_case_33;
			case 34:
			goto st_case_34;
			case 35:
			goto st_case_35;
			case 36:
			goto st_case_36;
			case 37:
			goto st_case_37;
			case 38:
			goto st_case_38;
			case 81:
			goto st_case_81;
			case 82:
			goto st_case_82;
			case 83:
			goto st_case_83;
			case 39:
			goto st_case_39;
			case 40:
			goto st_case_40;
			case 41:
			goto st_case_41;
			case 42:
			goto st_case_42;
			case 43:
			goto st_case_43;
			case 84:
			goto st_case_84;
			case 85:
			goto st_case_85;
			case 44:
			goto st_case_44;
			case 45:
			goto st_case_45;
			case 86:
			goto st_case_86;
			case 87:
			goto st_case_87;
			case 88:
			goto st_case_88;
			case 46:
			goto st_case_46;
			case 47:
			goto st_case_47;
			case 89:
			goto st_case_89;
			case 90:
			goto st_case_90;
			case 48:
			goto st_case_48;
			case 91:
			goto st_case_91;
			case 92:
			goto st_case_92;
			case 49:
			goto st_case_49;
			case 50:
			goto st_case_50;
			case 51:
			goto st_case_51;
			case 52:
			goto st_case_52;
			case 53:
			goto st_case_53;
			case 54:
			goto st_case_54;
			case 55:
			goto st_case_55;
			case 56:
			goto st_case_56;
			case 57:
			goto st_case_57;
			case 58:
			goto st_case_58;
			case 59:
			goto st_case_59;
			case 60:
			goto st_case_60;
			case 61:
			goto st_case_61;
			case 62:
			goto st_case_62;
			case 63:
			goto st_case_63;
			case 64:
			goto st_case_64;
			case 65:
			goto st_case_65;
			case 66:
			goto st_case_66;
			case 67:
			goto st_case_67;
			case 68:
			goto st_case_68;
			case 69:
			goto st_case_69;
			case 70:
			goto st_case_70;
			case 71:
			goto st_case_71;
			case 72:
			goto st_case_72;
			case 73:
			goto st_case_73;
			case 74:
			goto st_case_74;
			case 75:
			goto st_case_75;
			case 76:
			goto st_case_76;
			case 77:
			goto st_case_77;
			case 78:
			goto st_case_78;
			case 79:
			goto st_case_79;
			case 80:
			goto st_case_80;
			
		}
		goto st_out;
		_ctr1:
		{err = fmt.Errorf("invalid scheme: %q", data[:p])
			{p+= 1; cs = 1; goto _out;}
		}
		
		
		goto _st1;
		_st1:
		if p == eof  {
			{if cs >= 81  {
					goto _out;
					
				} else {
					goto _pop;
					
				}
			}
			
		}
		p+= 1;
		if p == pe  {
			goto _test_eof1;
			
		}
		st_case_1:
		switch (data[p ]) {
			case 85:
			{goto _st2;
			}
			case 117:
			{goto _st2;
			}
			
		}
		{goto _ctr2;
		}
		_ctr2:
		{err = fmt.Errorf("invalid scheme: %q", data[:p])
			{p+= 1; cs = 0; goto _out;}
		}
		
		
		goto _st0;
		_ctr11:
		{err = fmt.Errorf("invalid nid: bad char at pos %d: %+q", p, data[p])
			{p+= 1; cs = 0; goto _out;}
		}
		{err = fmt.Errorf("invalid nid: %q", data[b:p])
			{p+= 1; cs = 0; goto _out;}
		}
		
		
		goto _st0;
		_ctr106:
		{err = errors.New("invalid nid: too long")
			{p+= 1; cs = 0; goto _out;}
		}
		
		
		goto _st0;
		_ctr109:
		{err = fmt.Errorf("invalid nss: %q", data[b:p])
			{p+= 1; cs = 0; goto _out;}
		}
		
		
		goto _st0;
		_ctr133:
		{err = fmt.Errorf("invalid nid: bad char at pos %d: %+q", p, data[p])
			{p+= 1; cs = 0; goto _out;}
		}
		{err = errors.New("invalid nid: too long")
			{p+= 1; cs = 0; goto _out;}
		}
		
		
		goto _st0;
		st_case_0:
		_st0:
		cs = 0;
		goto _pop;
		_ctr4:
		{err = fmt.Errorf("invalid scheme: %q", data[:p])
			{p+= 1; cs = 2; goto _out;}
		}
		
		
		goto _st2;
		_st2:
		if p == eof  {
			{if cs >= 81  {
					goto _out;
					
				} else {
					goto _pop;
					
				}
			}
			
		}
		p+= 1;
		if p == pe  {
			goto _test_eof2;
			
		}
		st_case_2:
		switch (data[p ]) {
			case 82:
			{goto _st3;
			}
			case 114:
			{goto _st3;
			}
			
		}
		{goto _ctr2;
		}
		_ctr6:
		{err = fmt.Errorf("invalid scheme: %q", data[:p])
			{p+= 1; cs = 3; goto _out;}
		}
		
		
		goto _st3;
		_st3:
		if p == eof  {
			{if cs >= 81  {
					goto _out;
					
				} else {
					goto _pop;
					
				}
			}
			
		}
		p+= 1;
		if p == pe  {
			goto _test_eof3;
			
		}
		st_case_3:
		switch (data[p ]) {
			case 78:
			{goto _st4;
			}
			case 110:
			{goto _st4;
			}
			
		}
		{goto _ctr2;
		}
		_ctr8:
		{err = fmt.Errorf("invalid scheme: %q", data[:p])
			{p+= 1; cs = 4; goto _out;}
		}
		
		
		goto _st4;
		_st4:
		if p == eof  {
			{if cs >= 81  {
					goto _out;
					
				} else {
					goto _pop;
					
				}
			}
			
		}
		p+= 1;
		if p == pe  {
			goto _test_eof4;
			
		}
		st_case_4:
		if (data[p ])== 58  {
			{goto _st5;
			}
			
		}
		{goto _ctr2;
		}
		_ctr10:
		{err = fmt.Errorf("invalid nid: bad char at pos %d: %+q", p, data[p])
			{p+= 1; cs = 5; goto _out;}
		}
		{err = fmt.Errorf("invalid nid: %q", data[b:p])
			{p+= 1; cs = 5; goto _out;}
		}
		
		
		goto _st5;
		_st5:
		if p == eof  {
			{if cs >= 81  {
					goto _out;
					
				} else {
					goto _pop;
					
				}
			}
			
		}
		p+= 1;
		if p == pe  {
			goto _test_eof5;
			
		}
		st_case_5:
		if (data[p ])< 65  {
			{if 48 <= (data[p ])&& (data[p ])<= 57  {
					{goto _ctr12;
					}
					
				}
			}
			
		} else if (data[p ])> 90  {
			{if 97 <= (data[p ])&& (data[p ])<= 122  {
					{goto _ctr12;
					}
					
				}
			}
			
		} else {
			{goto _ctr12;
			}
			
		}
		{goto _ctr11;
		}
		_ctr13:
		{err = fmt.Errorf("invalid nid: bad char at pos %d: %+q", p, data[p])
			{p+= 1; cs = 6; goto _out;}
		}
		{err = fmt.Errorf("invalid nid: %q", data[b:p])
			{p+= 1; cs = 6; goto _out;}
		}
		
		
		goto _st6;
		_ctr12:
		{b = p
			pct = false
		}
		
		
		goto _st6;
		_st6:
		if p == eof  {
			{if cs >= 81  {
					goto _out;
					
				} else {
					goto _pop;
					
				}
			}
			
		}
		p+= 1;
		if p == pe  {
			goto _test_eof6;
			
		}
		st_case_6:
		if (data[p ])== 45  {
			{goto _st7;
			}
			
		}
		if (data[p ])< 65  {
			{if 48 <= (data[p ])&& (data[p ])<= 57  {
					{goto _st80;
					}
					
				}
			}
			
		} else if (data[p ])> 90  {
			{if 97 <= (data[p ])&& (data[p ])<= 122  {
					{goto _st80;
					}
					
				}
			}
			
		} else {
			{goto _st80;
			}
			
		}
		{goto _ctr11;
		}
		_ctr16:
		{err = fmt.Errorf("invalid nid: bad char at pos %d: %+q", p, data[p])
			{p+= 1; cs = 7; goto _out;}
		}
		{err = fmt.Errorf("invalid nid: %q", data[b:p])
			{p+= 1; cs = 7; goto _out;}
		}
		
		
		goto _st7;
		_st7:
		if p == eof  {
			{if cs >= 81  {
					goto _out;
					
				} else {
					goto _pop;
					
				}
			}
			
		}
		p+= 1;
		if p == pe  {
			goto _test_eof7;
			
		}
		st_case_7:
		if (data[p ])== 45  {
			{goto _st8;
			}
			
		}
		if (data[p ])< 65  {
			{if 48 <= (data[p ])&& (data[p ])<= 57  {
					{goto _st79;
					}
					
				}
			}
			
		} else if (data[p ])> 90  {
			{if 97 <= (data[p ])&& (data[p ])<= 122  {
					{goto _st79;
					}
					
				}
			}
			
		} else {
			{goto _st79;
			}
			
		}
		{goto _ctr11;
		}
		_ctr19:
		{err = fmt.Errorf("invalid nid: bad char at pos %d: %+q", p, data[p])
			{p+= 1; cs = 8; goto _out;}
		}
		{err = fmt.Errorf("invalid nid: %q", data[b:p])
			{p+= 1; cs = 8; goto _out;}
		}
		
		
		goto _st8;
		_st8:
		if p == eof  {
			{if cs >= 81  {
					goto _out;
					
				} else {
					goto _pop;
					
				}
			}
			
		}
		p+= 1;
		if p == pe  {
			goto _test_eof8;
			
		}
		st_case_8:
		if (data[p ])== 45  {
			{goto _st9;
			}
			
		}
		if (data[p ])< 65  {
			{if 48 <= (data[p ])&& (data[p ])<= 57  {
					{goto _st78;
					}
					
				}
			}
			
		} else if (data[p ])> 90  {
			{if 97 <= (data[p ])&& (data[p ])<= 122  {
					{goto _st78;
					}
					
				}
			}
			
		} else {
			{goto _st78;
			}
			
		}
		{goto _ctr11;
		}
		_ctr22:
		{err = fmt.Errorf("invalid nid: bad char at pos %d: %+q", p, data[p])
			{p+= 1; cs = 9; goto _out;}
		}
		{err = fmt.Errorf("invalid nid: %q", data[b:p])
			{p+= 1; cs = 9; goto _out;}
		}
		
		
		goto _st9;
		_st9:
		if p == eof  {
			{if cs >= 81  {
					goto _out;
					
				} else {
					goto _pop;
					
				}
			}
			
		}
		p+= 1;
		if p == pe  {
			goto _test_eof9;
			
		}
		st_case_9:
		if (data[p ])== 45  {
			{goto _st10;
			}
			
		}
		if (data[p ])< 65  {
			{if 48 <= (data[p ])&& (data[p ])<= 57  {
					{goto _st77;
					}
					
				}
			}
			
		} else if (data[p ])> 90  {
			{if 97 <= (data[p ])&& (data[p ])<= 122  {
					{goto _st77;
					}
					
				}
			}
			
		} else {
			{goto _st77;
			}
			
		}
		{goto _ctr11;
		}
		_ctr25:
		{err = fmt.Errorf("invalid nid: bad char at pos %d: %+q", p, data[p])
			{p+= 1; cs = 10; goto _out;}
		}
		{err = fmt.Errorf("invalid nid: %q", data[b:p])
			{p+= 1; cs = 10; goto _out;}
		}
		
		
		goto _st10;
		_st10:
		if p == eof  {
			{if cs >= 81  {
					goto _out;
					
				} else {
					goto _pop;
					
				}
			}
			
		}
		p+= 1;
		if p == pe  {
			goto _test_eof10;
			
		}
		st_case_10:
		if (data[p ])== 45  {
			{goto _st11;
			}
			
		}
		if (data[p ])< 65  {
			{if 48 <= (data[p ])&& (data[p ])<= 57  {
					{goto _st76;
					}
					
				}
			}
			
		} else if (data[p ])> 90  {
			{if 97 <= (data[p ])&& (data[p ])<= 122  {
					{goto _st76;
					}
					
				}
			}
			
		} else {
			{goto _st76;
			}
			
		}
		{goto _ctr11;
		}
		_ctr28:
		{err = fmt.Errorf("invalid nid: bad char at pos %d: %+q", p, data[p])
			{p+= 1; cs = 11; goto _out;}
		}
		{err = fmt.Errorf("invalid nid: %q", data[b:p])
			{p+= 1; cs = 11; goto _out;}
		}
		
		
		goto _st11;
		_st11:
		if p == eof  {
			{if cs >= 81  {
					goto _out;
					
				} else {
					goto _pop;
					
				}
			}
			
		}
		p+= 1;
		if p == pe  {
			goto _test_eof11;
			
		}
		st_case_11:
		if (data[p ])== 45  {
			{goto _st12;
			}
			
		}
		if (data[p ])< 65  {
			{if 48 <= (data[p ])&& (data[p ])<= 57  {
					{goto _st75;
					}
					
				}
			}
			
		} else if (data[p ])> 90  {
			{if 97 <= (data[p ])&& (data[p ])<= 122  {
					{goto _st75;
					}
					
				}
			}
			
		} else {
			{goto _st75;
			}
			
		}
		{goto _ctr11;
		}
		_ctr31:
		{err = fmt.Errorf("invalid nid: bad char at pos %d: %+q", p, data[p])
			{p+= 1; cs = 12; goto _out;}
		}
		{err = fmt.Errorf("invalid nid: %q", data[b:p])
			{p+= 1; cs = 12; goto _out;}
		}
		
		
		goto _st12;
		_st12:
		if p == eof  {
			{if cs >= 81  {
					goto _out;
					
				} else {
					goto _pop;
					
				}
			}
			
		}
		p+= 1;
		if p == pe  {
			goto _test_eof12;
			
		}
		st_case_12:
		if (data[p ])== 45  {
			{goto _st13;
			}
			
		}
		if (data[p ])< 65  {
			{if 48 <= (data[p ])&& (data[p ])<= 57  {
					{goto _st74;
					}
					
				}
			}
			
		} else if (data[p ])> 90  {
			{if 97 <= (data[p ])&& (data[p ])<= 122  {
					{goto _st74;
					}
					
				}
			}
			
		} else {
			{goto _st74;
			}
			
		}
		{goto _ctr11;
		}
		_ctr34:
		{err = fmt.Errorf("invalid nid: bad char at pos %d: %+q", p, data[p])
			{p+= 1; cs = 13; goto _out;}
		}
		{err = fmt.Errorf("invalid nid: %q", data[b:p])
			{p+= 1; cs = 13; goto _out;}
		}
		
		
		goto _st13;
		_st13:
		if p == eof  {
			{if cs >= 81  {
					goto _out;
					
				} else {
					goto _pop;
					
				}
			}
			
		}
		p+= 1;
		if p == pe  {
			goto _test_eof13;
			
		}
		st_case_13:
		if (data[p ])== 45  {
			{goto _st14;
			}
			
		}
		if (data[p ])< 65  {
			{if 48 <= (data[p ])&& (data[p ])<= 57  {
					{goto _st73;
					}
					
				}
			}
			
		} else if (data[p ])> 90  {
			{if 97 <= (data[p ])&& (data[p ])<= 122  {
					{goto _st73;
					}
					
				}
			}
			
		} else {
			{goto _st73;
			}
			
		}
		{goto _ctr11;
		}
		_ctr37:
		{err = fmt.Errorf("invalid nid: bad char at pos %d: %+q", p, data[p])
			{p+= 1; cs = 14; goto _out;}
		}
		{err = fmt.Errorf("invalid nid: %q", data[b:p])
			{p+= 1; cs = 14; goto _out;}
		}
		
		
		goto _st14;
		_st14:
		if p == eof  {
			{if cs >= 81  {
					goto _out;
					
				} else {
					goto _pop;
					
				}
			}
			
		}
		p+= 1;
		if p == pe  {
			goto _test_eof14;
			
		}
		st_case_14:
		if (data[p ])== 45  {
			{goto _st15;
			}
			
		}
		if (data[p ])< 65  {
			{if 48 <= (data[p ])&& (data[p ])<= 57  {
					{goto _st72;
					}
					
				}
			}
			
		} else if (data[p ])> 90  {
			{if 97 <= (data[p ])&& (data[p ])<= 122  {
					{goto _st72;
					}
					
				}
			}
			
		} else {
			{goto _st72;
			}
			
		}
		{goto _ctr11;
		}
		_ctr40:
		{err = fmt.Errorf("invalid nid: bad char at pos %d: %+q", p, data[p])
			{p+= 1; cs = 15; goto _out;}
		}
		{err = fmt.Errorf("invalid nid: %q", data[b:p])
			{p+= 1; cs = 15; goto _out;}
		}
		
		
		goto _st15;
		_st15:
		if p == eof  {
			{if cs >= 81  {
					goto _out;
					
				} else {
					goto _pop;
					
				}
			}
			
		}
		p+= 1;
		if p == pe  {
			goto _test_eof15;
			
		}
		st_case_15:
		if (data[p ])== 45  {
			{goto _st16;
			}
			
		}
		if (data[p ])< 65  {
			{if 48 <= (data[p ])&& (data[p ])<= 57  {
					{goto _st71;
					}
					
				}
			}
			
		} else if (data[p ])> 90  {
			{if 97 <= (data[p ])&& (data[p ])<= 122  {
					{goto _st71;
					}
					
				}
			}
			
		} else {
			{goto _st71;
			}
			
		}
		{goto _ctr11;
		}
		_ctr43:
		{err = fmt.Errorf("invalid nid: bad char at pos %d: %+q", p, data[p])
			{p+= 1; cs = 16; goto _out;}
		}
		{err = fmt.Errorf("invalid nid: %q", data[b:p])
			{p+= 1; cs = 16; goto _out;}
		}
		
		
		goto _st16;
		_st16:
		if p == eof  {
			{if cs >= 81  {
					goto _out;
					
				} else {
					goto _pop;
					
				}
			}
			
		}
		p+= 1;
		if p == pe  {
			goto _test_eof16;
			
		}
		st_case_16:
		if (data[p ])== 45  {
			{goto _st17;
			}
			
		}
		if (data[p ])< 65  {
			{if 48 <= (data[p ])&& (data[p ])<= 57  {
					{goto _st70;
					}
					
				}
			}
			
		} else if (data[p ])> 90  {
			{if 97 <= (data[p ])&& (data[p ])<= 122  {
					{goto _st70;
					}
					
				}
			}
			
		} else {
			{goto _st70;
			}
			
		}
		{goto _ctr11;
		}
		_ctr46:
		{err = fmt.Errorf("invalid nid: bad char at pos %d: %+q", p, data[p])
			{p+= 1; cs = 17; goto _out;}
		}
		{err = fmt.Errorf("invalid nid: %q", data[b:p])
			{p+= 1; cs = 17; goto _out;}
		}
		
		
		goto _st17;
		_st17:
		if p == eof  {
			{if cs >= 81  {
					goto _out;
					
				} else {
					goto _pop;
					
				}
			}
			
		}
		p+= 1;
		if p == pe  {
			goto _test_eof17;
			
		}
		st_case_17:
		if (data[p ])== 45  {
			{goto _st18;
			}
			
		}
		if (data[p ])< 65  {
			{if 48 <= (data[p ])&& (data[p ])<= 57  {
					{goto _st69;
					}
					
				}
			}
			
		} else if (data[p ])> 90  {
			{if 97 <= (data[p ])&& (data[p ])<= 122  {
					{goto _st69;
					}
					
				}
			}
			
		} else {
			{goto _st69;
			}
			
		}
		{goto _ctr11;
		}
		_ctr49:
		{err = fmt.Errorf("invalid nid: bad char at pos %d: %+q", p, data[p])
			{p+= 1; cs = 18; goto _out;}
		}
		{err = fmt.Errorf("invalid nid: %q", data[b:p])
			{p+= 1; cs = 18; goto _out;}
		}
		
		
		goto _st18;
		_st18:
		if p == eof  {
			{if cs >= 81  {
					goto _out;
					
				} else {
					goto _pop;
					
				}
			}
			
		}
		p+= 1;
		if p == pe  {
			goto _test_eof18;
			
		}
		st_case_18:
		if (data[p ])== 45  {
			{goto _st19;
			}
			
		}
		if (data[p ])< 65  {
			{if 48 <= (data[p ])&& (data[p ])<= 57  {
					{goto _st68;
					}
					
				}
			}
			
		} else if (data[p ])> 90  {
			{if 97 <= (data[p ])&& (data[p ])<= 122  {
					{goto _st68;
					}
					
				}
			}
			
		} else {
			{goto _st68;
			}
			
		}
		{goto _ctr11;
		}
		_ctr52:
		{err = fmt.Errorf("invalid nid: bad char at pos %d: %+q", p, data[p])
			{p+= 1; cs = 19; goto _out;}
		}
		{err = fmt.Errorf("invalid nid: %q", data[b:p])
			{p+= 1; cs = 19; goto _out;}
		}
		
		
		goto _st19;
		_st19:
		if p == eof  {
			{if cs >= 81  {
					goto _out;
					
				} else {
					goto _pop;
					
				}
			}
			
		}
		p+= 1;
		if p == pe  {
			goto _test_eof19;
			
		}
		st_case_19:
		if (data[p ])== 45  {
			{goto _st20;
			}
			
		}
		if (data[p ])< 65  {
			{if 48 <= (data[p ])&& (data[p ])<= 57  {
					{goto _st67;
					}
					
				}
			}
			
		} else if (data[p ])> 90  {
			{if 97 <= (data[p ])&& (data[p ])<= 122  {
					{goto _st67;
					}
					
				}
			}
			
		} else {
			{goto _st67;
			}
			
		}
		{goto _ctr11;
		}
		_ctr55:
		{err = fmt.Errorf("invalid nid: bad char at pos %d: %+q", p, data[p])
			{p+= 1; cs = 20; goto _out;}
		}
		{err = fmt.Errorf("invalid nid: %q", data[b:p])
			{p+= 1; cs = 20; goto _out;}
		}
		
		
		goto _st20;
		_st20:
		if p == eof  {
			{if cs >= 81  {
					goto _out;
					
				} else {
					goto _pop;
					
				}
			}
			
		}
		p+= 1;
		if p == pe  {
			goto _test_eof20;
			
		}
		st_case_20:
		if (data[p ])== 45  {
			{goto _st21;
			}
			
		}
		if (data[p ])< 65  {
			{if 48 <= (data[p ])&& (data[p ])<= 57  {
					{goto _st66;
					}
					
				}
			}
			
		} else if (data[p ])> 90  {
			{if 97 <= (data[p ])&& (data[p ])<= 122  {
					{goto _st66;
					}
					
				}
			}
			
		} else {
			{goto _st66;
			}
			
		}
		{goto _ctr11;
		}
		_ctr58:
		{err = fmt.Errorf("invalid nid: bad char at pos %d: %+q", p, data[p])
			{p+= 1; cs = 21; goto _out;}
		}
		{err = fmt.Errorf("invalid nid: %q", data[b:p])
			{p+= 1; cs = 21; goto _out;}
		}
		
		
		goto _st21;
		_st21:
		if p == eof  {
			{if cs >= 81  {
					goto _out;
					
				} else {
					goto _pop;
					
				}
			}
			
		}
		p+= 1;
		if p == pe  {
			goto _test_eof21;
			
		}
		st_case_21:
		if (data[p ])== 45  {
			{goto _st22;
			}
			
		}
		if (data[p ])< 65  {
			{if 48 <= (data[p ])&& (data[p ])<= 57  {
					{goto _st65;
					}
					
				}
			}
			
		} else if (data[p ])> 90  {
			{if 97 <= (data[p ])&& (data[p ])<= 122  {
					{goto _st65;
					}
					
				}
			}
			
		} else {
			{goto _st65;
			}
			
		}
		{goto _ctr11;
		}
		_ctr61:
		{err = fmt.Errorf("invalid nid: bad char at pos %d: %+q", p, data[p])
			{p+= 1; cs = 22; goto _out;}
		}
		{err = fmt.Errorf("invalid nid: %q", data[b:p])
			{p+= 1; cs = 22; goto _out;}
		}
		
		
		goto _st22;
		_st22:
		if p == eof  {
			{if cs >= 81  {
					goto _out;
					
				} else {
					goto _pop;
					
				}
			}
			
		}
		p+= 1;
		if p == pe  {
			goto _test_eof22;
			
		}
		st_case_22:
		if (data[p ])== 45  {
			{goto _st23;
			}
			
		}
		if (data[p ])< 65  {
			{if 48 <= (data[p ])&& (data[p ])<= 57  {
					{goto _st64;
					}
					
				}
			}
			
		} else if (data[p ])> 90  {
			{if 97 <= (data[p ])&& (data[p ])<= 122  {
					{goto _st64;
					}
					
				}
			}
			
		} else {
			{goto _st64;
			}
			
		}
		{goto _ctr11;
		}
		_ctr64:
		{err = fmt.Errorf("invalid nid: bad char at pos %d: %+q", p, data[p])
			{p+= 1; cs = 23; goto _out;}
		}
		{err = fmt.Errorf("invalid nid: %q", data[b:p])
			{p+= 1; cs = 23; goto _out;}
		}
		
		
		goto _st23;
		_st23:
		if p == eof  {
			{if cs >= 81  {
					goto _out;
					
				} else {
					goto _pop;
					
				}
			}
			
		}
		p+= 1;
		if p == pe  {
			goto _test_eof23;
			
		}
		st_case_23:
		if (data[p ])== 45  {
			{goto _st24;
			}
			
		}
		if (data[p ])< 65  {
			{if 48 <= (data[p ])&& (data[p ])<= 57  {
					{goto _st63;
					}
					
				}
			}
			
		} else if (data[p ])> 90  {
			{if 97 <= (data[p ])&& (data[p ])<= 122  {
					{goto _st63;
					}
					
				}
			}
			
		} else {
			{goto _st63;
			}
			
		}
		{goto _ctr11;
		}
		_ctr67:
		{err = fmt.Errorf("invalid nid: bad char at pos %d: %+q", p, data[p])
			{p+= 1; cs = 24; goto _out;}
		}
		{err = fmt.Errorf("invalid nid: %q", data[b:p])
			{p+= 1; cs = 24; goto _out;}
		}
		
		
		goto _st24;
		_st24:
		if p == eof  {
			{if cs >= 81  {
					goto _out;
					
				} else {
					goto _pop;
					
				}
			}
			
		}
		p+= 1;
		if p == pe  {
			goto _test_eof24;
			
		}
		st_case_24:
		if (data[p ])== 45  {
			{goto _st25;
			}
			
		}
		if (data[p ])< 65  {
			{if 48 <= (data[p ])&& (data[p ])<= 57  {
					{goto _st62;
					}
					
				}
			}
			
		} else if (data[p ])> 90  {
			{if 97 <= (data[p ])&& (data[p ])<= 122  {
					{goto _st62;
					}
					
				}
			}
			
		} else {
			{goto _st62;
			}
			
		}
		{goto _ctr11;
		}
		_ctr70:
		{err = fmt.Errorf("invalid nid: bad char at pos %d: %+q", p, data[p])
			{p+= 1; cs = 25; goto _out;}
		}
		{err = fmt.Errorf("invalid nid: %q", data[b:p])
			{p+= 1; cs = 25; goto _out;}
		}
		
		
		goto _st25;
		_st25:
		if p == eof  {
			{if cs >= 81  {
					goto _out;
					
				} else {
					goto _pop;
					
				}
			}
			
		}
		p+= 1;
		if p == pe  {
			goto _test_eof25;
			
		}
		st_case_25:
		if (data[p ])== 45  {
			{goto _st26;
			}
			
		}
		if (data[p ])< 65  {
			{if 48 <= (data[p ])&& (data[p ])<= 57  {
					{goto _st61;
					}
					
				}
			}
			
		} else if (data[p ])> 90  {
			{if 97 <= (data[p ])&& (data[p ])<= 122  {
					{goto _st61;
					}
					
				}
			}
			
		} else {
			{goto _st61;
			}
			
		}
		{goto _ctr11;
		}
		_ctr73:
		{err = fmt.Errorf("invalid nid: bad char at pos %d: %+q", p, data[p])
			{p+= 1; cs = 26; goto _out;}
		}
		{err = fmt.Errorf("invalid nid: %q", data[b:p])
			{p+= 1; cs = 26; goto _out;}
		}
		
		
		goto _st26;
		_st26:
		if p == eof  {
			{if cs >= 81  {
					goto _out;
					
				} else {
					goto _pop;
					
				}
			}
			
		}
		p+= 1;
		if p == pe  {
			goto _test_eof26;
			
		}
		st_case_26:
		if (data[p ])== 45  {
			{goto _st27;
			}
			
		}
		if (data[p ])< 65  {
			{if 48 <= (data[p ])&& (data[p ])<= 57  {
					{goto _st60;
					}
					
				}
			}
			
		} else if (data[p ])> 90  {
			{if 97 <= (data[p ])&& (data[p ])<= 122  {
					{goto _st60;
					}
					
				}
			}
			
		} else {
			{goto _st60;
			}
			
		}
		{goto _ctr11;
		}
		_ctr76:
		{err = fmt.Errorf("invalid nid: bad char at pos %d: %+q", p, data[p])
			{p+= 1; cs = 27; goto _out;}
		}
		{err = fmt.Errorf("invalid nid: %q", data[b:p])
			{p+= 1; cs = 27; goto _out;}
		}
		
		
		goto _st27;
		_st27:
		if p == eof  {
			{if cs >= 81  {
					goto _out;
					
				} else {
					goto _pop;
					
				}
			}
			
		}
		p+= 1;
		if p == pe  {
			goto _test_eof27;
			
		}
		st_case_27:
		if (data[p ])== 45  {
			{goto _st28;
			}
			
		}
		if (data[p ])< 65  {
			{if 48 <= (data[p ])&& (data[p ])<= 57  {
					{goto _st59;
					}
					
				}
			}
			
		} else if (data[p ])> 90  {
			{if 97 <= (data[p ])&& (data[p ])<= 122  {
					{goto _st59;
					}
					
				}
			}
			
		} else {
			{goto _st59;
			}
			
		}
		{goto _ctr11;
		}
		_ctr79:
		{err = fmt.Errorf("invalid nid: bad char at pos %d: %+q", p, data[p])
			{p+= 1; cs = 28; goto _out;}
		}
		{err = fmt.Errorf("invalid nid: %q", data[b:p])
			{p+= 1; cs = 28; goto _out;}
		}
		
		
		goto _st28;
		_st28:
		if p == eof  {
			{if cs >= 81  {
					goto _out;
					
				} else {
					goto _pop;
					
				}
			}
			
		}
		p+= 1;
		if p == pe  {
			goto _test_eof28;
			
		}
		st_case_28:
		if (data[p ])== 45  {
			{goto _st29;
			}
			
		}
		if (data[p ])< 65  {
			{if 48 <= (data[p ])&& (data[p ])<= 57  {
					{goto _st58;
					}
					
				}
			}
			
		} else if (data[p ])> 90  {
			{if 97 <= (data[p ])&& (data[p ])<= 122  {
					{goto _st58;
					}
					
				}
			}
			
		} else {
			{goto _st58;
			}
			
		}
		{goto _ctr11;
		}
		_ctr82:
		{err = fmt.Errorf("invalid nid: bad char at pos %d: %+q", p, data[p])
			{p+= 1; cs = 29; goto _out;}
		}
		{err = fmt.Errorf("invalid nid: %q", data[b:p])
			{p+= 1; cs = 29; goto _out;}
		}
		
		
		goto _st29;
		_st29:
		if p == eof  {
			{if cs >= 81  {
					goto _out;
					
				} else {
					goto _pop;
					
				}
			}
			
		}
		p+= 1;
		if p == pe  {
			goto _test_eof29;
			
		}
		st_case_29:
		if (data[p ])== 45  {
			{goto _st30;
			}
			
		}
		if (data[p ])< 65  {
			{if 48 <= (data[p ])&& (data[p ])<= 57  {
					{goto _st57;
					}
					
				}
			}
			
		} else if (data[p ])> 90  {
			{if 97 <= (data[p ])&& (data[p ])<= 122  {
					{goto _st57;
					}
					
				}
			}
			
		} else {
			{goto _st57;
			}
			
		}
		{goto _ctr11;
		}
		_ctr85:
		{err = fmt.Errorf("invalid nid: bad char at pos %d: %+q", p, data[p])
			{p+= 1; cs = 30; goto _out;}
		}
		{err = fmt.Errorf("invalid nid: %q", data[b:p])
			{p+= 1; cs = 30; goto _out;}
		}
		
		
		goto _st30;
		_st30:
		if p == eof  {
			{if cs >= 81  {
					goto _out;
					
				} else {
					goto _pop;
					
				}
			}
			
		}
		p+= 1;
		if p == pe  {
			goto _test_eof30;
			
		}
		st_case_30:
		if (data[p ])== 45  {
			{goto _st31;
			}
			
		}
		if (data[p ])< 65  {
			{if 48 <= (data[p ])&& (data[p ])<= 57  {
					{goto _st56;
					}
					
				}
			}
			
		} else if (data[p ])> 90  {
			{if 97 <= (data[p ])&& (data[p ])<= 122  {
					{goto _st56;
					}
					
				}
			}
			
		} else {
			{goto _st56;
			}
			
		}
		{goto _ctr11;
		}
		_ctr88:
		{err = fmt.Errorf("invalid nid: bad char at pos %d: %+q", p, data[p])
			{p+= 1; cs = 31; goto _out;}
		}
		{err = fmt.Errorf("invalid nid: %q", data[b:p])
			{p+= 1; cs = 31; goto _out;}
		}
		
		
		goto _st31;
		_st31:
		if p == eof  {
			{if cs >= 81  {
					goto _out;
					
				} else {
					goto _pop;
					
				}
			}
			
		}
		p+= 1;
		if p == pe  {
			goto _test_eof31;
			
		}
		st_case_31:
		if (data[p ])== 45  {
			{goto _st32;
			}
			
		}
		if (data[p ])< 65  {
			{if 48 <= (data[p ])&& (data[p ])<= 57  {
					{goto _st55;
					}
					
				}
			}
			
		} else if (data[p ])> 90  {
			{if 97 <= (data[p ])&& (data[p ])<= 122  {
					{goto _st55;
					}
					
				}
			}
			
		} else {
			{goto _st55;
			}
			
		}
		{goto _ctr11;
		}
		_ctr91:
		{err = fmt.Errorf("invalid nid: bad char at pos %d: %+q", p, data[p])
			{p+= 1; cs = 32; goto _out;}
		}
		{err = fmt.Errorf("invalid nid: %q", data[b:p])
			{p+= 1; cs = 32; goto _out;}
		}
		
		
		goto _st32;
		_st32:
		if p == eof  {
			{if cs >= 81  {
					goto _out;
					
				} else {
					goto _pop;
					
				}
			}
			
		}
		p+= 1;
		if p == pe  {
			goto _test_eof32;
			
		}
		st_case_32:
		if (data[p ])== 45  {
			{goto _st33;
			}
			
		}
		if (data[p ])< 65  {
			{if 48 <= (data[p ])&& (data[p ])<= 57  {
					{goto _st54;
					}
					
				}
			}
			
		} else if (data[p ])> 90  {
			{if 97 <= (data[p ])&& (data[p ])<= 122  {
					{goto _st54;
					}
					
				}
			}
			
		} else {
			{goto _st54;
			}
			
		}
		{goto _ctr11;
		}
		_ctr94:
		{err = fmt.Errorf("invalid nid: bad char at pos %d: %+q", p, data[p])
			{p+= 1; cs = 33; goto _out;}
		}
		{err = fmt.Errorf("invalid nid: %q", data[b:p])
			{p+= 1; cs = 33; goto _out;}
		}
		
		
		goto _st33;
		_st33:
		if p == eof  {
			{if cs >= 81  {
					goto _out;
					
				} else {
					goto _pop;
					
				}
			}
			
		}
		p+= 1;
		if p == pe  {
			goto _test_eof33;
			
		}
		st_case_33:
		if (data[p ])== 45  {
			{goto _st34;
			}
			
		}
		if (data[p ])< 65  {
			{if 48 <= (data[p ])&& (data[p ])<= 57  {
					{goto _st53;
					}
					
				}
			}
			
		} else if (data[p ])> 90  {
			{if 97 <= (data[p ])&& (data[p ])<= 122  {
					{goto _st53;
					}
					
				}
			}
			
		} else {
			{goto _st53;
			}
			
		}
		{goto _ctr11;
		}
		_ctr97:
		{err = fmt.Errorf("invalid nid: bad char at pos %d: %+q", p, data[p])
			{p+= 1; cs = 34; goto _out;}
		}
		{err = fmt.Errorf("invalid nid: %q", data[b:p])
			{p+= 1; cs = 34; goto _out;}
		}
		
		
		goto _st34;
		_st34:
		if p == eof  {
			{if cs >= 81  {
					goto _out;
					
				} else {
					goto _pop;
					
				}
			}
			
		}
		p+= 1;
		if p == pe  {
			goto _test_eof34;
			
		}
		st_case_34:
		if (data[p ])== 45  {
			{goto _st35;
			}
			
		}
		if (data[p ])< 65  {
			{if 48 <= (data[p ])&& (data[p ])<= 57  {
					{goto _st52;
					}
					
				}
			}
			
		} else if (data[p ])> 90  {
			{if 97 <= (data[p ])&& (data[p ])<= 122  {
					{goto _st52;
					}
					
				}
			}
			
		} else {
			{goto _st52;
			}
			
		}
		{goto _ctr11;
		}
		_ctr100:
		{err = fmt.Errorf("invalid nid: bad char at pos %d: %+q", p, data[p])
			{p+= 1; cs = 35; goto _out;}
		}
		{err = fmt.Errorf("invalid nid: %q", data[b:p])
			{p+= 1; cs = 35; goto _out;}
		}
		
		
		goto _st35;
		_st35:
		if p == eof  {
			{if cs >= 81  {
					goto _out;
					
				} else {
					goto _pop;
					
				}
			}
			
		}
		p+= 1;
		if p == pe  {
			goto _test_eof35;
			
		}
		st_case_35:
		if (data[p ])== 45  {
			{goto _st36;
			}
			
		}
		if (data[p ])< 65  {
			{if 48 <= (data[p ])&& (data[p ])<= 57  {
					{goto _st51;
					}
					
				}
			}
			
		} else if (data[p ])> 90  {
			{if 97 <= (data[p ])&& (data[p ])<= 122  {
					{goto _st51;
					}
					
				}
			}
			
		} else {
			{goto _st51;
			}
			
		}
		{goto _ctr11;
		}
		_ctr103:
		{err = fmt.Errorf("invalid nid: bad char at pos %d: %+q", p, data[p])
			{p+= 1; cs = 36; goto _out;}
		}
		{err = fmt.Errorf("invalid nid: %q", data[b:p])
			{p+= 1; cs = 36; goto _out;}
		}
		
		
		goto _st36;
		_st36:
		if p == eof  {
			{if cs >= 81  {
					goto _out;
					
				} else {
					goto _pop;
					
				}
			}
			
		}
		p+= 1;
		if p == pe  {
			goto _test_eof36;
			
		}
		st_case_36:
		if (data[p ])< 65  {
			{if 48 <= (data[p ])&& (data[p ])<= 57  {
					{goto _st37;
					}
					
				}
			}
			
		} else if (data[p ])> 90  {
			{if 97 <= (data[p ])&& (data[p ])<= 122  {
					{goto _st37;
					}
					
				}
			}
			
		} else {
			{goto _st37;
			}
			
		}
		{goto _ctr11;
		}
		_ctr105:
		{err = errors.New("invalid nid: too long")
			{p+= 1; cs = 37; goto _out;}
		}
		
		
		goto _st37;
		_st37:
		if p == eof  {
			{if cs >= 81  {
					goto _out;
					
				} else {
					goto _pop;
					
				}
			}
			
		}
		p+= 1;
		if p == pe  {
			goto _test_eof37;
			
		}
		st_case_37:
		if (data[p ])== 58  {
			{goto _ctr107;
			}
			
		}
		{goto _ctr106;
		}
		_ctr107:
		{out.setNID(data[b:p])
		}
		
		
		goto _st38;
		_ctr108:
		{err = fmt.Errorf("invalid nss: %q", data[b:p])
			{p+= 1; cs = 38; goto _out;}
		}
		
		
		goto _st38;
		_st38:
		if p == eof  {
			{if cs >= 81  {
					goto _out;
					
				} else {
					goto _pop;
					
				}
			}
			
		}
		p+= 1;
		if p == pe  {
			goto _test_eof38;
			
		}
		st_case_38:
		switch (data[p ]) {
			case 33:
			{goto _ctr110;
			}
			case 37:
			{goto _ctr111;
			}
			case 61:
			{goto _ctr110;
			}
			case 95:
			{goto _ctr110;
			}
			case 126:
			{goto _ctr110;
			}
			
		}
		if (data[p ])< 48  {
			{if 36 <= (data[p ])&& (data[p ])<= 46  {
					{goto _ctr110;
					}
					
				}
			}
			
		} else if (data[p ])> 59  {
			{if (data[p ])> 90  {
					{if 97 <= (data[p ])&& (data[p ])<= 122  {
							{goto _ctr110;
							}
							
						}
					}
					
				} else if (data[p ])>= 64  {
					{goto _ctr110;
					}
					
				}
			}
			
		} else {
			{goto _ctr110;
			}
			
		}
		{goto _ctr109;
		}
		_ctr110:
		{b = p
			pct = false
		}
		
		
		goto _st81;
		_ctr163:
		{out.setNSS(data[b:p])
		}
		
		
		goto _st81;
		_st81:
		if p == eof  {
			{if cs >= 81  {
					goto _out;
					
				} else {
					goto _pop;
					
				}
			}
			
		}
		p+= 1;
		if p == pe  {
			goto _test_eof81;
			
		}
		st_case_81:
		switch (data[p ]) {
			case 33:
			{goto _st81;
			}
			case 35:
			{goto _ctr164;
			}
			case 37:
			{goto _ctr165;
			}
			case 61:
			{goto _st81;
			}
			case 63:
			{goto _ctr166;
			}
			case 95:
			{goto _st81;
			}
			case 126:
			{goto _st81;
			}
			
		}
		if (data[p ])< 64  {
			{if 36 <= (data[p ])&& (data[p ])<= 59  {
					{goto _st81;
					}
					
				}
			}
			
		} else if (data[p ])> 90  {
			{if 97 <= (data[p ])&& (data[p ])<= 122  {
					{goto _st81;
					}
					
				}
			}
			
		} else {
			{goto _st81;
			}
			
		}
		{goto _st0;
		}
		_ctr164:
		{out.setNSS(data[b:p])
		}
		
		
		goto _st82;
		_ctr167:
		{b = p
			pct = false
		}
		{out.f = data[b:p]
		}
		
		
		goto _st82;
		_ctr174:
		{b = p
			pct = false
		}
		{out.r = data[b:p]
		}
		
		
		goto _st82;
		_ctr178:
		{out.r = data[b:p]
		}
		
		
		goto _st82;
		_ctr184:
		{out.r = data[b:p]
		}
		{b = p
			pct = false
		}
		{out.q = data[b:p]
		}
		
		
		goto _st82;
		_ctr187:
		{out.r = data[b:p]
		}
		{out.q = data[b:p]
		}
		
		
		goto _st82;
		_ctr195:
		{b = p
			pct = false
		}
		{out.q = data[b:p]
		}
		
		
		goto _st82;
		_ctr198:
		{out.q = data[b:p]
		}
		
		
		goto _st82;
		_st82:
		if p == eof  {
			{if cs >= 81  {
					goto _out;
					
				} else {
					goto _pop;
					
				}
			}
			
		}
		p+= 1;
		if p == pe  {
			goto _test_eof82;
			
		}
		st_case_82:
		switch (data[p ]) {
			case 33:
			{goto _ctr168;
			}
			case 37:
			{goto _ctr169;
			}
			case 61:
			{goto _ctr168;
			}
			case 95:
			{goto _ctr168;
			}
			case 126:
			{goto _ctr168;
			}
			
		}
		if (data[p ])< 48  {
			{if 36 <= (data[p ])&& (data[p ])<= 46  {
					{goto _ctr168;
					}
					
				}
			}
			
		} else if (data[p ])> 59  {
			{if (data[p ])> 90  {
					{if 97 <= (data[p ])&& (data[p ])<= 122  {
							{goto _ctr168;
							}
							
						}
					}
					
				} else if (data[p ])>= 64  {
					{goto _ctr168;
					}
					
				}
			}
			
		} else {
			{goto _ctr168;
			}
			
		}
		{goto _st0;
		}
		_ctr168:
		{b = p
			pct = false
		}
		
		
		goto _st83;
		_ctr170:
		{out.f = data[b:p]
		}
		
		
		goto _st83;
		_st83:
		if p == eof  {
			{if cs >= 81  {
					goto _out;
					
				} else {
					goto _pop;
					
				}
			}
			
		}
		p+= 1;
		if p == pe  {
			goto _test_eof83;
			
		}
		st_case_83:
		switch (data[p ]) {
			case 33:
			{goto _st83;
			}
			case 37:
			{goto _ctr171;
			}
			case 61:
			{goto _st83;
			}
			case 95:
			{goto _st83;
			}
			case 126:
			{goto _st83;
			}
			
		}
		if (data[p ])< 63  {
			{if 36 <= (data[p ])&& (data[p ])<= 59  {
					{goto _st83;
					}
					
				}
			}
			
		} else if (data[p ])> 90  {
			{if 97 <= (data[p ])&& (data[p ])<= 122  {
					{goto _st83;
					}
					
				}
			}
			
		} else {
			{goto _st83;
			}
			
		}
		{goto _st0;
		}
		_ctr169:
		{b = p
			pct = false
		}
		{pct = true
		}
		
		
		goto _st39;
		_ctr171:
		{pct = true
		}
		
		
		goto _st39;
		_st39:
		if p == eof  {
			{if cs >= 81  {
					goto _out;
					
				} else {
					goto _pop;
					
				}
			}
			
		}
		p+= 1;
		if p == pe  {
			goto _test_eof39;
			
		}
		st_case_39:
		if (data[p ])< 65  {
			{if 48 <= (data[p ])&& (data[p ])<= 57  {
					{goto _st40;
					}
					
				}
			}
			
		} else if (data[p ])> 70  {
			{if 97 <= (data[p ])&& (data[p ])<= 102  {
					{goto _st40;
					}
					
				}
			}
			
		} else {
			{goto _st40;
			}
			
		}
		{goto _st0;
		}
		_st40:
		if p == eof  {
			{if cs >= 81  {
					goto _out;
					
				} else {
					goto _pop;
					
				}
			}
			
		}
		p+= 1;
		if p == pe  {
			goto _test_eof40;
			
		}
		st_case_40:
		if (data[p ])< 65  {
			{if 48 <= (data[p ])&& (data[p ])<= 57  {
					{goto _st83;
					}
					
				}
			}
			
		} else if (data[p ])> 70  {
			{if 97 <= (data[p ])&& (data[p ])<= 102  {
					{goto _st83;
					}
					
				}
			}
			
		} else {
			{goto _st83;
			}
			
		}
		{goto _st0;
		}
		_ctr115:
		{err = fmt.Errorf("invalid nss: %q", data[b:p])
			{p+= 1; cs = 41; goto _out;}
		}
		
		
		goto _st41;
		_ctr111:
		{b = p
			pct = false
		}
		{pct = true
		}
		
		
		goto _st41;
		_ctr165:
		{pct = true
		}
		
		
		goto _st41;
		_st41:
		if p == eof  {
			{if cs >= 81  {
					goto _out;
					
				} else {
					goto _pop;
					
				}
			}
			
		}
		p+= 1;
		if p == pe  {
			goto _test_eof41;
			
		}
		st_case_41:
		if (data[p ])< 65  {
			{if 48 <= (data[p ])&& (data[p ])<= 57  {
					{goto _st42;
					}
					
				}
			}
			
		} else if (data[p ])> 70  {
			{if 97 <= (data[p ])&& (data[p ])<= 102  {
					{goto _st42;
					}
					
				}
			}
			
		} else {
			{goto _st42;
			}
			
		}
		{goto _ctr109;
		}
		_ctr117:
		{err = fmt.Errorf("invalid nss: %q", data[b:p])
			{p+= 1; cs = 42; goto _out;}
		}
		
		
		goto _st42;
		_st42:
		if p == eof  {
			{if cs >= 81  {
					goto _out;
					
				} else {
					goto _pop;
					
				}
			}
			
		}
		p+= 1;
		if p == pe  {
			goto _test_eof42;
			
		}
		st_case_42:
		if (data[p ])< 65  {
			{if 48 <= (data[p ])&& (data[p ])<= 57  {
					{goto _st81;
					}
					
				}
			}
			
		} else if (data[p ])> 70  {
			{if 97 <= (data[p ])&& (data[p ])<= 102  {
					{goto _st81;
					}
					
				}
			}
			
		} else {
			{goto _st81;
			}
			
		}
		{goto _ctr109;
		}
		_ctr166:
		{out.setNSS(data[b:p])
		}
		
		
		goto _st43;
		_st43:
		if p == eof  {
			{if cs >= 81  {
					goto _out;
					
				} else {
					goto _pop;
					
				}
			}
			
		}
		p+= 1;
		if p == pe  {
			goto _test_eof43;
			
		}
		st_case_43:
		switch (data[p ]) {
			case 43:
			{goto _st84;
			}
			case 61:
			{goto _st91;
			}
			
		}
		{goto _st0;
		}
		_ctr172:
		{b = p
			pct = false
		}
		{out.r = data[b:p]
		}
		
		
		goto _st84;
		_st84:
		if p == eof  {
			{if cs >= 81  {
					goto _out;
					
				} else {
					goto _pop;
					
				}
			}
			
		}
		p+= 1;
		if p == pe  {
			goto _test_eof84;
			
		}
		st_case_84:
		switch (data[p ]) {
			case 33:
			{goto _ctr173;
			}
			case 35:
			{goto _ctr174;
			}
			case 37:
			{goto _ctr175;
			}
			case 61:
			{goto _ctr173;
			}
			case 63:
			{goto _ctr176;
			}
			case 95:
			{goto _ctr173;
			}
			case 126:
			{goto _ctr173;
			}
			
		}
		if (data[p ])< 48  {
			{if 36 <= (data[p ])&& (data[p ])<= 46  {
					{goto _ctr173;
					}
					
				}
			}
			
		} else if (data[p ])> 59  {
			{if (data[p ])> 90  {
					{if 97 <= (data[p ])&& (data[p ])<= 122  {
							{goto _ctr173;
							}
							
						}
					}
					
				} else if (data[p ])>= 64  {
					{goto _ctr173;
					}
					
				}
			}
			
		} else {
			{goto _ctr173;
			}
			
		}
		{goto _st0;
		}
		_ctr173:
		{b = p
			pct = false
		}
		
		
		goto _st85;
		_ctr177:
		{out.r = data[b:p]
		}
		
		
		goto _st85;
		_st85:
		if p == eof  {
			{if cs >= 81  {
					goto _out;
					
				} else {
					goto _pop;
					
				}
			}
			
		}
		p+= 1;
		if p == pe  {
			goto _test_eof85;
			
		}
		st_case_85:
		switch (data[p ]) {
			case 33:
			{goto _st85;
			}
			case 35:
			{goto _ctr178;
			}
			case 37:
			{goto _ctr179;
			}
			case 61:
			{goto _st85;
			}
			case 63:
			{goto _ctr180;
			}
			case 95:
			{goto _st85;
			}
			case 126:
			{goto _st85;
			}
			
		}
		if (data[p ])< 64  {
			{if 36 <= (data[p ])&& (data[p ])<= 59  {
					{goto _st85;
					}
					
				}
			}
			
		} else if (data[p ])> 90  {
			{if 97 <= (data[p ])&& (data[p ])<= 122  {
					{goto _st85;
					}
					
				}
			}
			
		} else {
			{goto _st85;
			}
			
		}
		{goto _st0;
		}
		_ctr175:
		{b = p
			pct = false
		}
		{pct = true
		}
		
		
		goto _st44;
		_ctr179:
		{pct = true
		}
		
		
		goto _st44;
		_st44:
		if p == eof  {
			{if cs >= 81  {
					goto _out;
					
				} else {
					goto _pop;
					
				}
			}
			
		}
		p+= 1;
		if p == pe  {
			goto _test_eof44;
			
		}
		st_case_44:
		if (data[p ])< 65  {
			{if 48 <= (data[p ])&& (data[p ])<= 57  {
					{goto _st45;
					}
					
				}
			}
			
		} else if (data[p ])> 70  {
			{if 97 <= (data[p ])&& (data[p ])<= 102  {
					{goto _st45;
					}
					
				}
			}
			
		} else {
			{goto _st45;
			}
			
		}
		{goto _st0;
		}
		_st45:
		if p == eof  {
			{if cs >= 81  {
					goto _out;
					
				} else {
					goto _pop;
					
				}
			}
			
		}
		p+= 1;
		if p == pe  {
			goto _test_eof45;
			
		}
		st_case_45:
		if (data[p ])< 65  {
			{if 48 <= (data[p ])&& (data[p ])<= 57  {
					{goto _st85;
					}
					
				}
			}
			
		} else if (data[p ])> 70  {
			{if 97 <= (data[p ])&& (data[p ])<= 102  {
					{goto _st85;
					}
					
				}
			}
			
		} else {
			{goto _st85;
			}
			
		}
		{goto _st0;
		}
		_ctr180:
		{out.r = data[b:p]
		}
		
		
		goto _st86;
		_st86:
		if p == eof  {
			{if cs >= 81  {
					goto _out;
					
				} else {
					goto _pop;
					
				}
			}
			
		}
		p+= 1;
		if p == pe  {
			goto _test_eof86;
			
		}
		st_case_86:
		switch (data[p ]) {
			case 33:
			{goto _st85;
			}
			case 35:
			{goto _ctr178;
			}
			case 37:
			{goto _ctr179;
			}
			case 61:
			{goto _st87;
			}
			case 63:
			{goto _ctr180;
			}
			case 95:
			{goto _st85;
			}
			case 126:
			{goto _st85;
			}
			
		}
		if (data[p ])< 64  {
			{if 36 <= (data[p ])&& (data[p ])<= 59  {
					{goto _st85;
					}
					
				}
			}
			
		} else if (data[p ])> 90  {
			{if 97 <= (data[p ])&& (data[p ])<= 122  {
					{goto _st85;
					}
					
				}
			}
			
		} else {
			{goto _st85;
			}
			
		}
		{goto _st0;
		}
		_ctr182:
		{out.r = data[b:p]
		}
		{b = p
			pct = false
		}
		{out.q = data[b:p]
		}
		
		
		goto _st87;
		_st87:
		if p == eof  {
			{if cs >= 81  {
					goto _out;
					
				} else {
					goto _pop;
					
				}
			}
			
		}
		p+= 1;
		if p == pe  {
			goto _test_eof87;
			
		}
		st_case_87:
		switch (data[p ]) {
			case 33:
			{goto _ctr183;
			}
			case 35:
			{goto _ctr184;
			}
			case 37:
			{goto _ctr185;
			}
			case 47:
			{goto _st85;
			}
			case 61:
			{goto _ctr183;
			}
			case 63:
			{goto _ctr180;
			}
			case 95:
			{goto _ctr183;
			}
			case 126:
			{goto _ctr183;
			}
			
		}
		if (data[p ])< 64  {
			{if 36 <= (data[p ])&& (data[p ])<= 59  {
					{goto _ctr183;
					}
					
				}
			}
			
		} else if (data[p ])> 90  {
			{if 97 <= (data[p ])&& (data[p ])<= 122  {
					{goto _ctr183;
					}
					
				}
			}
			
		} else {
			{goto _ctr183;
			}
			
		}
		{goto _st0;
		}
		_ctr183:
		{b = p
			pct = false
		}
		
		
		goto _st88;
		_ctr186:
		{out.r = data[b:p]
		}
		{out.q = data[b:p]
		}
		
		
		goto _st88;
		_st88:
		if p == eof  {
			{if cs >= 81  {
					goto _out;
					
				} else {
					goto _pop;
					
				}
			}
			
		}
		p+= 1;
		if p == pe  {
			goto _test_eof88;
			
		}
		st_case_88:
		switch (data[p ]) {
			case 33:
			{goto _st88;
			}
			case 35:
			{goto _ctr187;
			}
			case 37:
			{goto _ctr188;
			}
			case 61:
			{goto _st88;
			}
			case 63:
			{goto _ctr189;
			}
			case 95:
			{goto _st88;
			}
			case 126:
			{goto _st88;
			}
			
		}
		if (data[p ])< 64  {
			{if 36 <= (data[p ])&& (data[p ])<= 59  {
					{goto _st88;
					}
					
				}
			}
			
		} else if (data[p ])> 90  {
			{if 97 <= (data[p ])&& (data[p ])<= 122  {
					{goto _st88;
					}
					
				}
			}
			
		} else {
			{goto _st88;
			}
			
		}
		{goto _st0;
		}
		_ctr188:
		{pct = true
		}
		
		
		goto _st46;
		_ctr185:
		{pct = true
		}
		{b = p
			pct = false
		}
		
		
		goto _st46;
		_st46:
		if p == eof  {
			{if cs >= 81  {
					goto _out;
					
				} else {
					goto _pop;
					
				}
			}
			
		}
		p+= 1;
		if p == pe  {
			goto _test_eof46;
			
		}
		st_case_46:
		if (data[p ])< 65  {
			{if 48 <= (data[p ])&& (data[p ])<= 57  {
					{goto _st47;
					}
					
				}
			}
			
		} else if (data[p ])> 70  {
			{if 97 <= (data[p ])&& (data[p ])<= 102  {
					{goto _st47;
					}
					
				}
			}
			
		} else {
			{goto _st47;
			}
			
		}
		{goto _st0;
		}
		_st47:
		if p == eof  {
			{if cs >= 81  {
					goto _out;
					
				} else {
					goto _pop;
					
				}
			}
			
		}
		p+= 1;
		if p == pe  {
			goto _test_eof47;
			
		}
		st_case_47:
		if (data[p ])< 65  {
			{if 48 <= (data[p ])&& (data[p ])<= 57  {
					{goto _st88;
					}
					
				}
			}
			
		} else if (data[p ])> 70  {
			{if 97 <= (data[p ])&& (data[p ])<= 102  {
					{goto _st88;
					}
					
				}
			}
			
		} else {
			{goto _st88;
			}
			
		}
		{goto _st0;
		}
		_ctr189:
		{out.r = data[b:p]
		}
		
		
		goto _st89;
		_ctr190:
		{out.r = data[b:p]
		}
		{out.q = data[b:p]
		}
		
		
		goto _st89;
		_st89:
		if p == eof  {
			{if cs >= 81  {
					goto _out;
					
				} else {
					goto _pop;
					
				}
			}
			
		}
		p+= 1;
		if p == pe  {
			goto _test_eof89;
			
		}
		st_case_89:
		switch (data[p ]) {
			case 33:
			{goto _st88;
			}
			case 35:
			{goto _ctr187;
			}
			case 37:
			{goto _ctr188;
			}
			case 61:
			{goto _st90;
			}
			case 63:
			{goto _ctr189;
			}
			case 95:
			{goto _st88;
			}
			case 126:
			{goto _st88;
			}
			
		}
		if (data[p ])< 64  {
			{if 36 <= (data[p ])&& (data[p ])<= 59  {
					{goto _st88;
					}
					
				}
			}
			
		} else if (data[p ])> 90  {
			{if 97 <= (data[p ])&& (data[p ])<= 122  {
					{goto _st88;
					}
					
				}
			}
			
		} else {
			{goto _st88;
			}
			
		}
		{goto _st0;
		}
		_ctr192:
		{out.r = data[b:p]
		}
		{b = p
			pct = false
		}
		{out.q = data[b:p]
		}
		
		
		goto _st90;
		_st90:
		if p == eof  {
			{if cs >= 81  {
					goto _out;
					
				} else {
					goto _pop;
					
				}
			}
			
		}
		p+= 1;
		if p == pe  {
			goto _test_eof90;
			
		}
		st_case_90:
		switch (data[p ]) {
			case 33:
			{goto _ctr183;
			}
			case 35:
			{goto _ctr184;
			}
			case 37:
			{goto _ctr185;
			}
			case 47:
			{goto _st88;
			}
			case 61:
			{goto _ctr183;
			}
			case 63:
			{goto _ctr189;
			}
			case 95:
			{goto _ctr183;
			}
			case 126:
			{goto _ctr183;
			}
			
		}
		if (data[p ])< 64  {
			{if 36 <= (data[p ])&& (data[p ])<= 59  {
					{goto _ctr183;
					}
					
				}
			}
			
		} else if (data[p ])> 90  {
			{if 97 <= (data[p ])&& (data[p ])<= 122  {
					{goto _ctr183;
					}
					
				}
			}
			
		} else {
			{goto _ctr183;
			}
			
		}
		{goto _st0;
		}
		_ctr176:
		{b = p
			pct = false
		}
		{out.r = data[b:p]
		}
		
		
		goto _st48;
		_st48:
		if p == eof  {
			{if cs >= 81  {
					goto _out;
					
				} else {
					goto _pop;
					
				}
			}
			
		}
		p+= 1;
		if p == pe  {
			goto _test_eof48;
			
		}
		st_case_48:
		if (data[p ])== 61  {
			{goto _st91;
			}
			
		}
		{goto _st0;
		}
		_ctr193:
		{b = p
			pct = false
		}
		{out.q = data[b:p]
		}
		
		
		goto _st91;
		_st91:
		if p == eof  {
			{if cs >= 81  {
					goto _out;
					
				} else {
					goto _pop;
					
				}
			}
			
		}
		p+= 1;
		if p == pe  {
			goto _test_eof91;
			
		}
		st_case_91:
		switch (data[p ]) {
			case 33:
			{goto _ctr194;
			}
			case 35:
			{goto _ctr195;
			}
			case 37:
			{goto _ctr196;
			}
			case 61:
			{goto _ctr194;
			}
			case 95:
			{goto _ctr194;
			}
			case 126:
			{goto _ctr194;
			}
			
		}
		if (data[p ])< 48  {
			{if 36 <= (data[p ])&& (data[p ])<= 46  {
					{goto _ctr194;
					}
					
				}
			}
			
		} else if (data[p ])> 59  {
			{if (data[p ])> 90  {
					{if 97 <= (data[p ])&& (data[p ])<= 122  {
							{goto _ctr194;
							}
							
						}
					}
					
				} else if (data[p ])>= 64  {
					{goto _ctr194;
					}
					
				}
			}
			
		} else {
			{goto _ctr194;
			}
			
		}
		{goto _st0;
		}
		_ctr194:
		{b = p
			pct = false
		}
		
		
		goto _st92;
		_ctr197:
		{out.q = data[b:p]
		}
		
		
		goto _st92;
		_st92:
		if p == eof  {
			{if cs >= 81  {
					goto _out;
					
				} else {
					goto _pop;
					
				}
			}
			
		}
		p+= 1;
		if p == pe  {
			goto _test_eof92;
			
		}
		st_case_92:
		switch (data[p ]) {
			case 33:
			{goto _st92;
			}
			case 35:
			{goto _ctr198;
			}
			case 37:
			{goto _ctr199;
			}
			case 61:
			{goto _st92;
			}
			case 95:
			{goto _st92;
			}
			case 126:
			{goto _st92;
			}
			
		}
		if (data[p ])< 63  {
			{if 36 <= (data[p ])&& (data[p ])<= 59  {
					{goto _st92;
					}
					
				}
			}
			
		} else if (data[p ])> 90  {
			{if 97 <= (data[p ])&& (data[p ])<= 122  {
					{goto _st92;
					}
					
				}
			}
			
		} else {
			{goto _st92;
			}
			
		}
		{goto _st0;
		}
		_ctr196:
		{b = p
			pct = false
		}
		{pct = true
		}
		
		
		goto _st49;
		_ctr199:
		{pct = true
		}
		
		
		goto _st49;
		_st49:
		if p == eof  {
			{if cs >= 81  {
					goto _out;
					
				} else {
					goto _pop;
					
				}
			}
			
		}
		p+= 1;
		if p == pe  {
			goto _test_eof49;
			
		}
		st_case_49:
		if (data[p ])< 65  {
			{if 48 <= (data[p ])&& (data[p ])<= 57  {
					{goto _st50;
					}
					
				}
			}
			
		} else if (data[p ])> 70  {
			{if 97 <= (data[p ])&& (data[p ])<= 102  {
					{goto _st50;
					}
					
				}
			}
			
		} else {
			{goto _st50;
			}
			
		}
		{goto _st0;
		}
		_st50:
		if p == eof  {
			{if cs >= 81  {
					goto _out;
					
				} else {
					goto _pop;
					
				}
			}
			
		}
		p+= 1;
		if p == pe  {
			goto _test_eof50;
			
		}
		st_case_50:
		if (data[p ])< 65  {
			{if 48 <= (data[p ])&& (data[p ])<= 57  {
					{goto _st92;
					}
					
				}
			}
			
		} else if (data[p ])> 70  {
			{if 97 <= (data[p ])&& (data[p ])<= 102  {
					{goto _st92;
					}
					
				}
			}
			
		} else {
			{goto _st92;
			}
			
		}
		{goto _st0;
		}
		_ctr132:
		{err = fmt.Errorf("invalid nid: bad char at pos %d: %+q", p, data[p])
			{p+= 1; cs = 51; goto _out;}
		}
		{err = errors.New("invalid nid: too long")
			{p+= 1; cs = 51; goto _out;}
		}
		
		
		goto _st51;
		_st51:
		if p == eof  {
			{if cs >= 81  {
					goto _out;
					
				} else {
					goto _pop;
					
				}
			}
			
		}
		p+= 1;
		if p == pe  {
			goto _test_eof51;
			
		}
		st_case_51:
		if (data[p ])== 58  {
			{goto _ctr107;
			}
			
		}
		if (data[p ])< 65  {
			{if 48 <= (data[p ])&& (data[p ])<= 57  {
					{goto _st37;
					}
					
				}
			}
			
		} else if (data[p ])> 90  {
			{if 97 <= (data[p ])&& (data[p ])<= 122  {
					{goto _st37;
					}
					
				}
			}
			
		} else {
			{goto _st37;
			}
			
		}
		{goto _ctr133;
		}
		_ctr134:
		{err = fmt.Errorf("invalid nid: bad char at pos %d: %+q", p, data[p])
			{p+= 1; cs = 52; goto _out;}
		}
		{err = errors.New("invalid nid: too long")
			{p+= 1; cs = 52; goto _out;}
		}
		
		
		goto _st52;
		_st52:
		if p == eof  {
			{if cs >= 81  {
					goto _out;
					
				} else {
					goto _pop;
					
				}
			}
			
		}
		p+= 1;
		if p == pe  {
			goto _test_eof52;
			
		}
		st_case_52:
		switch (data[p ]) {
			case 45:
			{goto _st36;
			}
			case 58:
			{goto _ctr107;
			}
			
		}
		if (data[p ])< 65  {
			{if 48 <= (data[p ])&& (data[p ])<= 57  {
					{goto _st51;
					}
					
				}
			}
			
		} else if (data[p ])> 90  {
			{if 97 <= (data[p ])&& (data[p ])<= 122  {
					{goto _st51;
					}
					
				}
			}
			
		} else {
			{goto _st51;
			}
			
		}
		{goto _ctr133;
		}
		_ctr135:
		{err = fmt.Errorf("invalid nid: bad char at pos %d: %+q", p, data[p])
			{p+= 1; cs = 53; goto _out;}
		}
		{err = errors.New("invalid nid: too long")
			{p+= 1; cs = 53; goto _out;}
		}
		
		
		goto _st53;
		_st53:
		if p == eof  {
			{if cs >= 81  {
					goto _out;
					
				} else {
					goto _pop;
					
				}
			}
			
		}
		p+= 1;
		if p == pe  {
			goto _test_eof53;
			
		}
		st_case_53:
		switch (data[p ]) {
			case 45:
			{goto _st35;
			}
			case 58:
			{goto _ctr107;
			}
			
		}
		if (data[p ])< 65  {
			{if 48 <= (data[p ])&& (data[p ])<= 57  {
					{goto _st52;
					}
					
				}
			}
			
		} else if (data[p ])> 90  {
			{if 97 <= (data[p ])&& (data[p ])<= 122  {
					{goto _st52;
					}
					
				}
			}
			
		} else {
			{goto _st52;
			}
			
		}
		{goto _ctr133;
		}
		_ctr136:
		{err = fmt.Errorf("invalid nid: bad char at pos %d: %+q", p, data[p])
			{p+= 1; cs = 54; goto _out;}
		}
		{err = errors.New("invalid nid: too long")
			{p+= 1; cs = 54; goto _out;}
		}
		
		
		goto _st54;
		_st54:
		if p == eof  {
			{if cs >= 81  {
					goto _out;
					
				} else {
					goto _pop;
					
				}
			}
			
		}
		p+= 1;
		if p == pe  {
			goto _test_eof54;
			
		}
		st_case_54:
		switch (data[p ]) {
			case 45:
			{goto _st34;
			}
			case 58:
			{goto _ctr107;
			}
			
		}
		if (data[p ])< 65  {
			{if 48 <= (data[p ])&& (data[p ])<= 57  {
					{goto _st53;
					}
					
				}
			}
			
		} else if (data[p ])> 90  {
			{if 97 <= (data[p ])&& (data[p ])<= 122  {
					{goto _st53;
					}
					
				}
			}
			
		} else {
			{goto _st53;
			}
			
		}
		{goto _ctr133;
		}
		_ctr137:
		{err = fmt.Errorf("invalid nid: bad char at pos %d: %+q", p, data[p])
			{p+= 1; cs = 55; goto _out;}
		}
		{err = errors.New("invalid nid: too long")
			{p+= 1; cs = 55; goto _out;}
		}
		
		
		goto _st55;
		_st55:
		if p == eof  {
			{if cs >= 81  {
					goto _out;
					
				} else {
					goto _pop;
					
				}
			}
			
		}
		p+= 1;
		if p == pe  {
			goto _test_eof55;
			
		}
		st_case_55:
		switch (data[p ]) {
			case 45:
			{goto _st33;
			}
			case 58:
			{goto _ctr107;
			}
			
		}
		if (data[p ])< 65  {
			{if 48 <= (data[p ])&& (data[p ])<= 57  {
					{goto _st54;
					}
					
				}
			}
			
		} else if (data[p ])> 90  {
			{if 97 <= (data[p ])&& (data[p ])<= 122  {
					{goto _st54;
					}
					
				}
			}
			
		} else {
			{goto _st54;
			}
			
		}
		{goto _ctr133;
		}
		_ctr138:
		{err = fmt.Errorf("invalid nid: bad char at pos %d: %+q", p, data[p])
			{p+= 1; cs = 56; goto _out;}
		}
		{err = errors.New("invalid nid: too long")
			{p+= 1; cs = 56; goto _out;}
		}
		
		
		goto _st56;
		_st56:
		if p == eof  {
			{if cs >= 81  {
					goto _out;
					
				} else {
					goto _pop;
					
				}
			}
			
		}
		p+= 1;
		if p == pe  {
			goto _test_eof56;
			
		}
		st_case_56:
		switch (data[p ]) {
			case 45:
			{goto _st32;
			}
			case 58:
			{goto _ctr107;
			}
			
		}
		if (data[p ])< 65  {
			{if 48 <= (data[p ])&& (data[p ])<= 57  {
					{goto _st55;
					}
					
				}
			}
			
		} else if (data[p ])> 90  {
			{if 97 <= (data[p ])&& (data[p ])<= 122  {
					{goto _st55;
					}
					
				}
			}
			
		} else {
			{goto _st55;
			}
			
		}
		{goto _ctr133;
		}
		_ctr139:
		{err = fmt.Errorf("invalid nid: bad char at pos %d: %+q", p, data[p])
			{p+= 1; cs = 57; goto _out;}
		}
		{err = errors.New("invalid nid: too long")
			{p+= 1; cs = 57; goto _out;}
		}
		
		
		goto _st57;
		_st57:
		if p == eof  {
			{if cs >= 81  {
					goto _out;
					
				} else {
					goto _pop;
					
				}
			}
			
		}
		p+= 1;
		if p == pe  {
			goto _test_eof57;
			
		}
		st_case_57:
		switch (data[p ]) {
			case 45:
			{goto _st31;
			}
			case 58:
			{goto _ctr107;
			}
			
		}
		if (data[p ])< 65  {
			{if 48 <= (data[p ])&& (data[p ])<= 57  {
					{goto _st56;
					}
					
				}
			}
			
		} else if (data[p ])> 90  {
			{if 97 <= (data[p ])&& (data[p ])<= 122  {
					{goto _st56;
					}
					
				}
			}
			
		} else {
			{goto _st56;
			}
			
		}
		{goto _ctr133;
		}
		_ctr140:
		{err = fmt.Errorf("invalid nid: bad char at pos %d: %+q", p, data[p])
			{p+= 1; cs = 58; goto _out;}
		}
		{err = errors.New("invalid nid: too long")
			{p+= 1; cs = 58; goto _out;}
		}
		
		
		goto _st58;
		_st58:
		if p == eof  {
			{if cs >= 81  {
					goto _out;
					
				} else {
					goto _pop;
					
				}
			}
			
		}
		p+= 1;
		if p == pe  {
			goto _test_eof58;
			
		}
		st_case_58:
		switch (data[p ]) {
			case 45:
			{goto _st30;
			}
			case 58:
			{goto _ctr107;
			}
			
		}
		if (data[p ])< 65  {
			{if 48 <= (data[p ])&& (data[p ])<= 57  {
					{goto _st57;
					}
					
				}
			}
			
		} else if (data[p ])> 90  {
			{if 97 <= (data[p ])&& (data[p ])<= 122  {
					{goto _st57;
					}
					
				}
			}
			
		} else {
			{goto _st57;
			}
			
		}
		{goto _ctr133;
		}
		_ctr141:
		{err = fmt.Errorf("invalid nid: bad char at pos %d: %+q", p, data[p])
			{p+= 1; cs = 59; goto _out;}
		}
		{err = errors.New("invalid nid: too long")
			{p+= 1; cs = 59; goto _out;}
		}
		
		
		goto _st59;
		_st59:
		if p == eof  {
			{if cs >= 81  {
					goto _out;
					
				} else {
					goto _pop;
					
				}
			}
			
		}
		p+= 1;
		if p == pe  {
			goto _test_eof59;
			
		}
		st_case_59:
		switch (data[p ]) {
			case 45:
			{goto _st29;
			}
			case 58:
			{goto _ctr107;
			}
			
		}
		if (data[p ])< 65  {
			{if 48 <= (data[p ])&& (data[p ])<= 57  {
					{goto _st58;
					}
					
				}
			}
			
		} else if (data[p ])> 90  {
			{if 97 <= (data[p ])&& (data[p ])<= 122  {
					{goto _st58;
					}
					
				}
			}
			
		} else {
			{goto _st58;
			}
			
		}
		{goto _ctr133;
		}
		_ctr142:
		{err = fmt.Errorf("invalid nid: bad char at pos %d: %+q", p, data[p])
			{p+= 1; cs = 60; goto _out;}
		}
		{err = errors.New("invalid nid: too long")
			{p+= 1; cs = 60; goto _out;}
		}
		
		
		goto _st60;
		_st60:
		if p == eof  {
			{if cs >= 81  {
					goto _out;
					
				} else {
					goto _pop;
					
				}
			}
			
		}
		p+= 1;
		if p == pe  {
			goto _test_eof60;
			
		}
		st_case_60:
		switch (data[p ]) {
			case 45:
			{goto _st28;
			}
			case 58:
			{goto _ctr107;
			}
			
		}
		if (data[p ])< 65  {
			{if 48 <= (data[p ])&& (data[p ])<= 57  {
					{goto _st59;
					}
					
				}
			}
			
		} else if (data[p ])> 90  {
			{if 97 <= (data[p ])&& (data[p ])<= 122  {
					{goto _st59;
					}
					
				}
			}
			
		} else {
			{goto _st59;
			}
			
		}
		{goto _ctr133;
		}
		_ctr143:
		{err = fmt.Errorf("invalid nid: bad char at pos %d: %+q", p, data[p])
			{p+= 1; cs = 61; goto _out;}
		}
		{err = errors.New("invalid nid: too long")
			{p+= 1; cs = 61; goto _out;}
		}
		
		
		goto _st61;
		_st61:
		if p == eof  {
			{if cs >= 81  {
					goto _out;
					
				} else {
					goto _pop;
					
				}
			}
			
		}
		p+= 1;
		if p == pe  {
			goto _test_eof61;
			
		}
		st_case_61:
		switch (data[p ]) {
			case 45:
			{goto _st27;
			}
			case 58:
			{goto _ctr107;
			}
			
		}
		if (data[p ])< 65  {
			{if 48 <= (data[p ])&& (data[p ])<= 57  {
					{goto _st60;
					}
					
				}
			}
			
		} else if (data[p ])> 90  {
			{if 97 <= (data[p ])&& (data[p ])<= 122  {
					{goto _st60;
					}
					
				}
			}
			
		} else {
			{goto _st60;
			}
			
		}
		{goto _ctr133;
		}
		_ctr144:
		{err = fmt.Errorf("invalid nid: bad char at pos %d: %+q", p, data[p])
			{p+= 1; cs = 62; goto _out;}
		}
		{err = errors.New("invalid nid: too long")
			{p+= 1; cs = 62; goto _out;}
		}
		
		
		goto _st62;
		_st62:
		if p == eof  {
			{if cs >= 81  {
					goto _out;
					
				} else {
					goto _pop;
					
				}
			}
			
		}
		p+= 1;
		if p == pe  {
			goto _test_eof62;
			
		}
		st_case_62:
		switch (data[p ]) {
			case 45:
			{goto _st26;
			}
			case 58:
			{goto _ctr107;
			}
			
		}
		if (data[p ])< 65  {
			{if 48 <= (data[p ])&& (data[p ])<= 57  {
					{goto _st61;
					}
					
				}
			}
			
		} else if (data[p ])> 90  {
			{if 97 <= (data[p ])&& (data[p ])<= 122  {
					{goto _st61;
					}
					
				}
			}
			
		} else {
			{goto _st61;
			}
			
		}
		{goto _ctr133;
		}
		_ctr145:
		{err = fmt.Errorf("invalid nid: bad char at pos %d: %+q", p, data[p])
			{p+= 1; cs = 63; goto _out;}
		}
		{err = errors.New("invalid nid: too long")
			{p+= 1; cs = 63; goto _out;}
		}
		
		
		goto _st63;
		_st63:
		if p == eof  {
			{if cs >= 81  {
					goto _out;
					
				} else {
					goto _pop;
					
				}
			}
			
		}
		p+= 1;
		if p == pe  {
			goto _test_eof63;
			
		}
		st_case_63:
		switch (data[p ]) {
			case 45:
			{goto _st25;
			}
			case 58:
			{goto _ctr107;
			}
			
		}
		if (data[p ])< 65  {
			{if 48 <= (data[p ])&& (data[p ])<= 57  {
					{goto _st62;
					}
					
				}
			}
			
		} else if (data[p ])> 90  {
			{if 97 <= (data[p ])&& (data[p ])<= 122  {
					{goto _st62;
					}
					
				}
			}
			
		} else {
			{goto _st62;
			}
			
		}
		{goto _ctr133;
		}
		_ctr146:
		{err = fmt.Errorf("invalid nid: bad char at pos %d: %+q", p, data[p])
			{p+= 1; cs = 64; goto _out;}
		}
		{err = errors.New("invalid nid: too long")
			{p+= 1; cs = 64; goto _out;}
		}
		
		
		goto _st64;
		_st64:
		if p == eof  {
			{if cs >= 81  {
					goto _out;
					
				} else {
					goto _pop;
					
				}
			}
			
		}
		p+= 1;
		if p == pe  {
			goto _test_eof64;
			
		}
		st_case_64:
		switch (data[p ]) {
			case 45:
			{goto _st24;
			}
			case 58:
			{goto _ctr107;
			}
			
		}
		if (data[p ])< 65  {
			{if 48 <= (data[p ])&& (data[p ])<= 57  {
					{goto _st63;
					}
					
				}
			}
			
		} else if (data[p ])> 90  {
			{if 97 <= (data[p ])&& (data[p ])<= 122  {
					{goto _st63;
					}
					
				}
			}
			
		} else {
			{goto _st63;
			}
			
		}
		{goto _ctr133;
		}
		_ctr147:
		{err = fmt.Errorf("invalid nid: bad char at pos %d: %+q", p, data[p])
			{p+= 1; cs = 65; goto _out;}
		}
		{err = errors.New("invalid nid: too long")
			{p+= 1; cs = 65; goto _out;}
		}
		
		
		goto _st65;
		_st65:
		if p == eof  {
			{if cs >= 81  {
					goto _out;
					
				} else {
					goto _pop;
					
				}
			}
			
		}
		p+= 1;
		if p == pe  {
			goto _test_eof65;
			
		}
		st_case_65:
		switch (data[p ]) {
			case 45:
			{goto _st23;
			}
			case 58:
			{goto _ctr107;
			}
			
		}
		if (data[p ])< 65  {
			{if 48 <= (data[p ])&& (data[p ])<= 57  {
					{goto _st64;
					}
					
				}
			}
			
		} else if (data[p ])> 90  {
			{if 97 <= (data[p ])&& (data[p ])<= 122  {
					{goto _st64;
					}
					
				}
			}
			
		} else {
			{goto _st64;
			}
			
		}
		{goto _ctr133;
		}
		_ctr148:
		{err = fmt.Errorf("invalid nid: bad char at pos %d: %+q", p, data[p])
			{p+= 1; cs = 66; goto _out;}
		}
		{err = errors.New("invalid nid: too long")
			{p+= 1; cs = 66; goto _out;}
		}
		
		
		goto _st66;
		_st66:
		if p == eof  {
			{if cs >= 81  {
					goto _out;
					
				} else {
					goto _pop;
					
				}
			}
			
		}
		p+= 1;
		if p == pe  {
			goto _test_eof66;
			
		}
		st_case_66:
		switch (data[p ]) {
			case 45:
			{goto _st22;
			}
			case 58:
			{goto _ctr107;
			}
			
		}
		if (data[p ])< 65  {
			{if 48 <= (data[p ])&& (data[p ])<= 57  {
					{goto _st65;
					}
					
				}
			}
			
		} else if (data[p ])> 90  {
			{if 97 <= (data[p ])&& (data[p ])<= 122  {
					{goto _st65;
					}
					
				}
			}
			
		} else {
			{goto _st65;
			}
			
		}
		{goto _ctr133;
		}
		_ctr149:
		{err = fmt.Errorf("invalid nid: bad char at pos %d: %+q", p, data[p])
			{p+= 1; cs = 67; goto _out;}
		}
		{err = errors.New("invalid nid: too long")
			{p+= 1; cs = 67; goto _out;}
		}
		
		
		goto _st67;
		_st67:
		if p == eof  {
			{if cs >= 81  {
					goto _out;
					
				} else {
					goto _pop;
					
				}
			}
			
		}
		p+= 1;
		if p == pe  {
			goto _test_eof67;
			
		}
		st_case_67:
		switch (data[p ]) {
			case 45:
			{goto _st21;
			}
			case 58:
			{goto _ctr107;
			}
			
		}
		if (data[p ])< 65  {
			{if 48 <= (data[p ])&& (data[p ])<= 57  {
					{goto _st66;
					}
					
				}
			}
			
		} else if (data[p ])> 90  {
			{if 97 <= (data[p ])&& (data[p ])<= 122  {
					{goto _st66;
					}
					
				}
			}
			
		} else {
			{goto _st66;
			}
			
		}
		{goto _ctr133;
		}
		_ctr150:
		{err = fmt.Errorf("invalid nid: bad char at pos %d: %+q", p, data[p])
			{p+= 1; cs = 68; goto _out;}
		}
		{err = errors.New("invalid nid: too long")
			{p+= 1; cs = 68; goto _out;}
		}
		
		
		goto _st68;
		_st68:
		if p == eof  {
			{if cs >= 81  {
					goto _out;
					
				} else {
					goto _pop;
					
				}
			}
			
		}
		p+= 1;
		if p == pe  {
			goto _test_eof68;
			
		}
		st_case_68:
		switch (data[p ]) {
			case 45:
			{goto _st20;
			}
			case 58:
			{goto _ctr107;
			}
			
		}
		if (data[p ])< 65  {
			{if 48 <= (data[p ])&& (data[p ])<= 57  {
					{goto _st67;
					}
					
				}
			}
			
		} else if (data[p ])> 90  {
			{if 97 <= (data[p ])&& (data[p ])<= 122  {
					{goto _st67;
					}
					
				}
			}
			
		} else {
			{goto _st67;
			}
			
		}
		{goto _ctr133;
		}
		_ctr151:
		{err = fmt.Errorf("invalid nid: bad char at pos %d: %+q", p, data[p])
			{p+= 1; cs = 69; goto _out;}
		}
		{err = errors.New("invalid nid: too long")
			{p+= 1; cs = 69; goto _out;}
		}
		
		
		goto _st69;
		_st69:
		if p == eof  {
			{if cs >= 81  {
					goto _out;
					
				} else {
					goto _pop;
					
				}
			}
			
		}
		p+= 1;
		if p == pe  {
			goto _test_eof69;
			
		}
		st_case_69:
		switch (data[p ]) {
			case 45:
			{goto _st19;
			}
			case 58:
			{goto _ctr107;
			}
			
		}
		if (data[p ])< 65  {
			{if 48 <= (data[p ])&& (data[p ])<= 57  {
					{goto _st68;
					}
					
				}
			}
			
		} else if (data[p ])> 90  {
			{if 97 <= (data[p ])&& (data[p ])<= 122  {
					{goto _st68;
					}
					
				}
			}
			
		} else {
			{goto _st68;
			}
			
		}
		{goto _ctr133;
		}
		_ctr152:
		{err = fmt.Errorf("invalid nid: bad char at pos %d: %+q", p, data[p])
			{p+= 1; cs = 70; goto _out;}
		}
		{err = errors.New("invalid nid: too long")
			{p+= 1; cs = 70; goto _out;}
		}
		
		
		goto _st70;
		_st70:
		if p == eof  {
			{if cs >= 81  {
					goto _out;
					
				} else {
					goto _pop;
					
				}
			}
			
		}
		p+= 1;
		if p == pe  {
			goto _test_eof70;
			
		}
		st_case_70:
		switch (data[p ]) {
			case 45:
			{goto _st18;
			}
			case 58:
			{goto _ctr107;
			}
			
		}
		if (data[p ])< 65  {
			{if 48 <= (data[p ])&& (data[p ])<= 57  {
					{goto _st69;
					}
					
				}
			}
			
		} else if (data[p ])> 90  {
			{if 97 <= (data[p ])&& (data[p ])<= 122  {
					{goto _st69;
					}
					
				}
			}
			
		} else {
			{goto _st69;
			}
			
		}
		{goto _ctr133;
		}
		_ctr153:
		{err = fmt.Errorf("invalid nid: bad char at pos %d: %+q", p, data[p])
			{p+= 1; cs = 71; goto _out;}
		}
		{err = errors.New("invalid nid: too long")
			{p+= 1; cs = 71; goto _out;}
		}
		
		
		goto _st71;
		_st71:
		if p == eof  {
			{if cs >= 81  {
					goto _out;
					
				} else {
					goto _pop;
					
				}
			}
			
		}
		p+= 1;
		if p == pe  {
			goto _test_eof71;
			
		}
		st_case_71:
		switch (data[p ]) {
			case 45:
			{goto _st17;
			}
			case 58:
			{goto _ctr107;
			}
			
		}
		if (data[p ])< 65  {
			{if 48 <= (data[p ])&& (data[p ])<= 57  {
					{goto _st70;
					}
					
				}
			}
			
		} else if (data[p ])> 90  {
			{if 97 <= (data[p ])&& (data[p ])<= 122  {
					{goto _st70;
					}
					
				}
			}
			
		} else {
			{goto _st70;
			}
			
		}
		{goto _ctr133;
		}
		_ctr154:
		{err = fmt.Errorf("invalid nid: bad char at pos %d: %+q", p, data[p])
			{p+= 1; cs = 72; goto _out;}
		}
		{err = errors.New("invalid nid: too long")
			{p+= 1; cs = 72; goto _out;}
		}
		
		
		goto _st72;
		_st72:
		if p == eof  {
			{if cs >= 81  {
					goto _out;
					
				} else {
					goto _pop;
					
				}
			}
			
		}
		p+= 1;
		if p == pe  {
			goto _test_eof72;
			
		}
		st_case_72:
		switch (data[p ]) {
			case 45:
			{goto _st16;
			}
			case 58:
			{goto _ctr107;
			}
			
		}
		if (data[p ])< 65  {
			{if 48 <= (data[p ])&& (data[p ])<= 57  {
					{goto _st71;
					}
					
				}
			}
			
		} else if (data[p ])> 90  {
			{if 97 <= (data[p ])&& (data[p ])<= 122  {
					{goto _st71;
					}
					
				}
			}
			
		} else {
			{goto _st71;
			}
			
		}
		{goto _ctr133;
		}
		_ctr155:
		{err = fmt.Errorf("invalid nid: bad char at pos %d: %+q", p, data[p])
			{p+= 1; cs = 73; goto _out;}
		}
		{err = errors.New("invalid nid: too long")
			{p+= 1; cs = 73; goto _out;}
		}
		
		
		goto _st73;
		_st73:
		if p == eof  {
			{if cs >= 81  {
					goto _out;
					
				} else {
					goto _pop;
					
				}
			}
			
		}
		p+= 1;
		if p == pe  {
			goto _test_eof73;
			
		}
		st_case_73:
		switch (data[p ]) {
			case 45:
			{goto _st15;
			}
			case 58:
			{goto _ctr107;
			}
			
		}
		if (data[p ])< 65  {
			{if 48 <= (data[p ])&& (data[p ])<= 57  {
					{goto _st72;
					}
					
				}
			}
			
		} else if (data[p ])> 90  {
			{if 97 <= (data[p ])&& (data[p ])<= 122  {
					{goto _st72;
					}
					
				}
			}
			
		} else {
			{goto _st72;
			}
			
		}
		{goto _ctr133;
		}
		_ctr156:
		{err = fmt.Errorf("invalid nid: bad char at pos %d: %+q", p, data[p])
			{p+= 1; cs = 74; goto _out;}
		}
		{err = errors.New("invalid nid: too long")
			{p+= 1; cs = 74; goto _out;}
		}
		
		
		goto _st74;
		_st74:
		if p == eof  {
			{if cs >= 81  {
					goto _out;
					
				} else {
					goto _pop;
					
				}
			}
			
		}
		p+= 1;
		if p == pe  {
			goto _test_eof74;
			
		}
		st_case_74:
		switch (data[p ]) {
			case 45:
			{goto _st14;
			}
			case 58:
			{goto _ctr107;
			}
			
		}
		if (data[p ])< 65  {
			{if 48 <= (data[p ])&& (data[p ])<= 57  {
					{goto _st73;
					}
					
				}
			}
			
		} else if (data[p ])> 90  {
			{if 97 <= (data[p ])&& (data[p ])<= 122  {
					{goto _st73;
					}
					
				}
			}
			
		} else {
			{goto _st73;
			}
			
		}
		{goto _ctr133;
		}
		_ctr157:
		{err = fmt.Errorf("invalid nid: bad char at pos %d: %+q", p, data[p])
			{p+= 1; cs = 75; goto _out;}
		}
		{err = errors.New("invalid nid: too long")
			{p+= 1; cs = 75; goto _out;}
		}
		
		
		goto _st75;
		_st75:
		if p == eof  {
			{if cs >= 81  {
					goto _out;
					
				} else {
					goto _pop;
					
				}
			}
			
		}
		p+= 1;
		if p == pe  {
			goto _test_eof75;
			
		}
		st_case_75:
		switch (data[p ]) {
			case 45:
			{goto _st13;
			}
			case 58:
			{goto _ctr107;
			}
			
		}
		if (data[p ])< 65  {
			{if 48 <= (data[p ])&& (data[p ])<= 57  {
					{goto _st74;
					}
					
				}
			}
			
		} else if (data[p ])> 90  {
			{if 97 <= (data[p ])&& (data[p ])<= 122  {
					{goto _st74;
					}
					
				}
			}
			
		} else {
			{goto _st74;
			}
			
		}
		{goto _ctr133;
		}
		_ctr158:
		{err = fmt.Errorf("invalid nid: bad char at pos %d: %+q", p, data[p])
			{p+= 1; cs = 76; goto _out;}
		}
		{err = errors.New("invalid nid: too long")
			{p+= 1; cs = 76; goto _out;}
		}
		
		
		goto _st76;
		_st76:
		if p == eof  {
			{if cs >= 81  {
					goto _out;
					
				} else {
					goto _pop;
					
				}
			}
			
		}
		p+= 1;
		if p == pe  {
			goto _test_eof76;
			
		}
		st_case_76:
		switch (data[p ]) {
			case 45:
			{goto _st12;
			}
			case 58:
			{goto _ctr107;
			}
			
		}
		if (data[p ])< 65  {
			{if 48 <= (data[p ])&& (data[p ])<= 57  {
					{goto _st75;
					}
					
				}
			}
			
		} else if (data[p ])> 90  {
			{if 97 <= (data[p ])&& (data[p ])<= 122  {
					{goto _st75;
					}
					
				}
			}
			
		} else {
			{goto _st75;
			}
			
		}
		{goto _ctr133;
		}
		_ctr159:
		{err = fmt.Errorf("invalid nid: bad char at pos %d: %+q", p, data[p])
			{p+= 1; cs = 77; goto _out;}
		}
		{err = errors.New("invalid nid: too long")
			{p+= 1; cs = 77; goto _out;}
		}
		
		
		goto _st77;
		_st77:
		if p == eof  {
			{if cs >= 81  {
					goto _out;
					
				} else {
					goto _pop;
					
				}
			}
			
		}
		p+= 1;
		if p == pe  {
			goto _test_eof77;
			
		}
		st_case_77:
		switch (data[p ]) {
			case 45:
			{goto _st11;
			}
			case 58:
			{goto _ctr107;
			}
			
		}
		if (data[p ])< 65  {
			{if 48 <= (data[p ])&& (data[p ])<= 57  {
					{goto _st76;
					}
					
				}
			}
			
		} else if (data[p ])> 90  {
			{if 97 <= (data[p ])&& (data[p ])<= 122  {
					{goto _st76;
					}
					
				}
			}
			
		} else {
			{goto _st76;
			}
			
		}
		{goto _ctr133;
		}
		_ctr160:
		{err = fmt.Errorf("invalid nid: bad char at pos %d: %+q", p, data[p])
			{p+= 1; cs = 78; goto _out;}
		}
		{err = errors.New("invalid nid: too long")
			{p+= 1; cs = 78; goto _out;}
		}
		
		
		goto _st78;
		_st78:
		if p == eof  {
			{if cs >= 81  {
					goto _out;
					
				} else {
					goto _pop;
					
				}
			}
			
		}
		p+= 1;
		if p == pe  {
			goto _test_eof78;
			
		}
		st_case_78:
		switch (data[p ]) {
			case 45:
			{goto _st10;
			}
			case 58:
			{goto _ctr107;
			}
			
		}
		if (data[p ])< 65  {
			{if 48 <= (data[p ])&& (data[p ])<= 57  {
					{goto _st77;
					}
					
				}
			}
			
		} else if (data[p ])> 90  {
			{if 97 <= (data[p ])&& (data[p ])<= 122  {
					{goto _st77;
					}
					
				}
			}
			
		} else {
			{goto _st77;
			}
			
		}
		{goto _ctr133;
		}
		_ctr161:
		{err = fmt.Errorf("invalid nid: bad char at pos %d: %+q", p, data[p])
			{p+= 1; cs = 79; goto _out;}
		}
		{err = errors.New("invalid nid: too long")
			{p+= 1; cs = 79; goto _out;}
		}
		
		
		goto _st79;
		_st79:
		if p == eof  {
			{if cs >= 81  {
					goto _out;
					
				} else {
					goto _pop;
					
				}
			}
			
		}
		p+= 1;
		if p == pe  {
			goto _test_eof79;
			
		}
		st_case_79:
		switch (data[p ]) {
			case 45:
			{goto _st9;
			}
			case 58:
			{goto _ctr107;
			}
			
		}
		if (data[p ])< 65  {
			{if 48 <= (data[p ])&& (data[p ])<= 57  {
					{goto _st78;
					}
					
				}
			}
			
		} else if (data[p ])> 90  {
			{if 97 <= (data[p ])&& (data[p ])<= 122  {
					{goto _st78;
					}
					
				}
			}
			
		} else {
			{goto _st78;
			}
			
		}
		{goto _ctr133;
		}
		_ctr162:
		{err = fmt.Errorf("invalid nid: bad char at pos %d: %+q", p, data[p])
			{p+= 1; cs = 80; goto _out;}
		}
		{err = errors.New("invalid nid: too long")
			{p+= 1; cs = 80; goto _out;}
		}
		
		
		goto _st80;
		_st80:
		if p == eof  {
			{if cs >= 81  {
					goto _out;
					
				} else {
					goto _pop;
					
				}
			}
			
		}
		p+= 1;
		if p == pe  {
			goto _test_eof80;
			
		}
		st_case_80:
		switch (data[p ]) {
			case 45:
			{goto _st8;
			}
			case 58:
			{goto _ctr107;
			}
			
		}
		if (data[p ])< 65  {
			{if 48 <= (data[p ])&& (data[p ])<= 57  {
					{goto _st79;
					}
					
				}
			}
			
		} else if (data[p ])> 90  {
			{if 97 <= (data[p ])&& (data[p ])<= 122  {
					{goto _st79;
					}
					
				}
			}
			
		} else {
			{goto _st79;
			}
			
		}
		{goto _ctr133;
		}
		st_out:
		_test_eof1: cs = 1;
		goto _test_eof; 
		_test_eof2: cs = 2;
		goto _test_eof; 
		_test_eof3: cs = 3;
		goto _test_eof; 
		_test_eof4: cs = 4;
		goto _test_eof; 
		_test_eof5: cs = 5;
		goto _test_eof; 
		_test_eof6: cs = 6;
		goto _test_eof; 
		_test_eof7: cs = 7;
		goto _test_eof; 
		_test_eof8: cs = 8;
		goto _test_eof; 
		_test_eof9: cs = 9;
		goto _test_eof; 
		_test_eof10: cs = 10;
		goto _test_eof; 
		_test_eof11: cs = 11;
		goto _test_eof; 
		_test_eof12: cs = 12;
		goto _test_eof; 
		_test_eof13: cs = 13;
		goto _test_eof; 
		_test_eof14: cs = 14;
		goto _test_eof; 
		_test_eof15: cs = 15;
		goto _test_eof; 
		_test_eof16: cs = 16;
		goto _test_eof; 
		_test_eof17: cs = 17;
		goto _test_eof; 
		_test_eof18: cs = 18;
		goto _test_eof; 
		_test_eof19: cs = 19;
		goto _test_eof; 
		_test_eof20: cs = 20;
		goto _test_eof; 
		_test_eof21: cs = 21;
		goto _test_eof; 
		_test_eof22: cs = 22;
		goto _test_eof; 
		_test_eof23: cs = 23;
		goto _test_eof; 
		_test_eof24: cs = 24;
		goto _test_eof; 
		_test_eof25: cs = 25;
		goto _test_eof; 
		_test_eof26: cs = 26;
		goto _test_eof; 
		_test_eof27: cs = 27;
		goto _test_eof; 
		_test_eof28: cs = 28;
		goto _test_eof; 
		_test_eof29: cs = 29;
		goto _test_eof; 
		_test_eof30: cs = 30;
		goto _test_eof; 
		_test_eof31: cs = 31;
		goto _test_eof; 
		_test_eof32: cs = 32;
		goto _test_eof; 
		_test_eof33: cs = 33;
		goto _test_eof; 
		_test_eof34: cs = 34;
		goto _test_eof; 
		_test_eof35: cs = 35;
		goto _test_eof; 
		_test_eof36: cs = 36;
		goto _test_eof; 
		_test_eof37: cs = 37;
		goto _test_eof; 
		_test_eof38: cs = 38;
		goto _test_eof; 
		_test_eof81: cs = 81;
		goto _test_eof; 
		_test_eof82: cs = 82;
		goto _test_eof; 
		_test_eof83: cs = 83;
		goto _test_eof; 
		_test_eof39: cs = 39;
		goto _test_eof; 
		_test_eof40: cs = 40;
		goto _test_eof; 
		_test_eof41: cs = 41;
		goto _test_eof; 
		_test_eof42: cs = 42;
		goto _test_eof; 
		_test_eof43: cs = 43;
		goto _test_eof; 
		_test_eof84: cs = 84;
		goto _test_eof; 
		_test_eof85: cs = 85;
		goto _test_eof; 
		_test_eof44: cs = 44;
		goto _test_eof; 
		_test_eof45: cs = 45;
		goto _test_eof; 
		_test_eof86: cs = 86;
		goto _test_eof; 
		_test_eof87: cs = 87;
		goto _test_eof; 
		_test_eof88: cs = 88;
		goto _test_eof; 
		_test_eof46: cs = 46;
		goto _test_eof; 
		_test_eof47: cs = 47;
		goto _test_eof; 
		_test_eof89: cs = 89;
		goto _test_eof; 
		_test_eof90: cs = 90;
		goto _test_eof; 
		_test_eof48: cs = 48;
		goto _test_eof; 
		_test_eof91: cs = 91;
		goto _test_eof; 
		_test_eof92: cs = 92;
		goto _test_eof; 
		_test_eof49: cs = 49;
		goto _test_eof; 
		_test_eof50: cs = 50;
		goto _test_eof; 
		_test_eof51: cs = 51;
		goto _test_eof; 
		_test_eof52: cs = 52;
		goto _test_eof; 
		_test_eof53: cs = 53;
		goto _test_eof; 
		_test_eof54: cs = 54;
		goto _test_eof; 
		_test_eof55: cs = 55;
		goto _test_eof; 
		_test_eof56: cs = 56;
		goto _test_eof; 
		_test_eof57: cs = 57;
		goto _test_eof; 
		_test_eof58: cs = 58;
		goto _test_eof; 
		_test_eof59: cs = 59;
		goto _test_eof; 
		_test_eof60: cs = 60;
		goto _test_eof; 
		_test_eof61: cs = 61;
		goto _test_eof; 
		_test_eof62: cs = 62;
		goto _test_eof; 
		_test_eof63: cs = 63;
		goto _test_eof; 
		_test_eof64: cs = 64;
		goto _test_eof; 
		_test_eof65: cs = 65;
		goto _test_eof; 
		_test_eof66: cs = 66;
		goto _test_eof; 
		_test_eof67: cs = 67;
		goto _test_eof; 
		_test_eof68: cs = 68;
		goto _test_eof; 
		_test_eof69: cs = 69;
		goto _test_eof; 
		_test_eof70: cs = 70;
		goto _test_eof; 
		_test_eof71: cs = 71;
		goto _test_eof; 
		_test_eof72: cs = 72;
		goto _test_eof; 
		_test_eof73: cs = 73;
		goto _test_eof; 
		_test_eof74: cs = 74;
		goto _test_eof; 
		_test_eof75: cs = 75;
		goto _test_eof; 
		_test_eof76: cs = 76;
		goto _test_eof; 
		_test_eof77: cs = 77;
		goto _test_eof; 
		_test_eof78: cs = 78;
		goto _test_eof; 
		_test_eof79: cs = 79;
		goto _test_eof; 
		_test_eof80: cs = 80;
		goto _test_eof; 
		
		_test_eof: {}
		if p == eof  {
			{switch cs  {
					case 1:
					{break;
					}
					case 0:
					{break;
					}
					case 2:
					{break;
					}
					case 3:
					{break;
					}
					case 4:
					{break;
					}
					case 5:
					{break;
					}
					case 6:
					{break;
					}
					case 7:
					{break;
					}
					case 8:
					{break;
					}
					case 9:
					{break;
					}
					case 10:
					{break;
					}
					case 11:
					{break;
					}
					case 12:
					{break;
					}
					case 13:
					{break;
					}
					case 14:
					{break;
					}
					case 15:
					{break;
					}
					case 16:
					{break;
					}
					case 17:
					{break;
					}
					case 18:
					{break;
					}
					case 19:
					{break;
					}
					case 20:
					{break;
					}
					case 21:
					{break;
					}
					case 22:
					{break;
					}
					case 23:
					{break;
					}
					case 24:
					{break;
					}
					case 25:
					{break;
					}
					case 26:
					{break;
					}
					case 27:
					{break;
					}
					case 28:
					{break;
					}
					case 29:
					{break;
					}
					case 30:
					{break;
					}
					case 31:
					{break;
					}
					case 32:
					{break;
					}
					case 33:
					{break;
					}
					case 34:
					{break;
					}
					case 35:
					{break;
					}
					case 36:
					{break;
					}
					case 37:
					{break;
					}
					case 38:
					{break;
					}
					case 81:
					{break;
					}
					case 82:
					{break;
					}
					case 83:
					{break;
					}
					case 39:
					{break;
					}
					case 40:
					{break;
					}
					case 41:
					{break;
					}
					case 42:
					{break;
					}
					case 43:
					{break;
					}
					case 84:
					{break;
					}
					case 85:
					{break;
					}
					case 44:
					{break;
					}
					case 45:
					{break;
					}
					case 86:
					{break;
					}
					case 87:
					{break;
					}
					case 88:
					{break;
					}
					case 46:
					{break;
					}
					case 47:
					{break;
					}
					case 89:
					{break;
					}
					case 90:
					{break;
					}
					case 48:
					{break;
					}
					case 91:
					{break;
					}
					case 92:
					{break;
					}
					case 49:
					{break;
					}
					case 50:
					{break;
					}
					case 51:
					{break;
					}
					case 52:
					{break;
					}
					case 53:
					{break;
					}
					case 54:
					{break;
					}
					case 55:
					{break;
					}
					case 56:
					{break;
					}
					case 57:
					{break;
					}
					case 58:
					{break;
					}
					case 59:
					{break;
					}
					case 60:
					{break;
					}
					case 61:
					{break;
					}
					case 62:
					{break;
					}
					case 63:
					{break;
					}
					case 64:
					{break;
					}
					case 65:
					{break;
					}
					case 66:
					{break;
					}
					case 67:
					{break;
					}
					case 68:
					{break;
					}
					case 69:
					{break;
					}
					case 70:
					{break;
					}
					case 71:
					{break;
					}
					case 72:
					{break;
					}
					case 73:
					{break;
					}
					case 74:
					{break;
					}
					case 75:
					{break;
					}
					case 76:
					{break;
					}
					case 77:
					{break;
					}
					case 78:
					{break;
					}
					case 79:
					{break;
					}
					case 80:
					{break;
					}
					
				}
				switch cs  {
				
				}
				switch cs  {
					case 1:
					goto _ctr1;case 0:
					goto _st0;case 2:
					goto _ctr4;case 3:
					goto _ctr6;case 4:
					goto _ctr8;case 5:
					goto _ctr10;case 6:
					goto _ctr13;case 7:
					goto _ctr16;case 8:
					goto _ctr19;case 9:
					goto _ctr22;case 10:
					goto _ctr25;case 11:
					goto _ctr28;case 12:
					goto _ctr31;case 13:
					goto _ctr34;case 14:
					goto _ctr37;case 15:
					goto _ctr40;case 16:
					goto _ctr43;case 17:
					goto _ctr46;case 18:
					goto _ctr49;case 19:
					goto _ctr52;case 20:
					goto _ctr55;case 21:
					goto _ctr58;case 22:
					goto _ctr61;case 23:
					goto _ctr64;case 24:
					goto _ctr67;case 25:
					goto _ctr70;case 26:
					goto _ctr73;case 27:
					goto _ctr76;case 28:
					goto _ctr79;case 29:
					goto _ctr82;case 30:
					goto _ctr85;case 31:
					goto _ctr88;case 32:
					goto _ctr91;case 33:
					goto _ctr94;case 34:
					goto _ctr97;case 35:
					goto _ctr100;case 36:
					goto _ctr103;case 37:
					goto _ctr105;case 38:
					goto _ctr108;case 81:
					goto _ctr163;case 82:
					goto _ctr167;case 83:
					goto _ctr170;case 39:
					goto _st39;case 40:
					goto _st40;case 41:
					goto _ctr115;case 42:
					goto _ctr117;case 43:
					goto _st43;case 84:
					goto _ctr172;case 85:
					goto _ctr177;case 44:
					goto _st44;case 45:
					goto _st45;case 86:
					goto _ctr180;case 87:
					goto _ctr182;case 88:
					goto _ctr186;case 46:
					goto _st46;case 47:
					goto _st47;case 89:
					goto _ctr190;case 90:
					goto _ctr192;case 48:
					goto _st48;case 91:
					goto _ctr193;case 92:
					goto _ctr197;case 49:
					goto _st49;case 50:
					goto _st50;case 51:
					goto _ctr132;case 52:
					goto _ctr134;case 53:
					goto _ctr135;case 54:
					goto _ctr136;case 55:
					goto _ctr137;case 56:
					goto _ctr138;case 57:
					goto _ctr139;case 58:
					goto _ctr140;case 59:
					goto _ctr141;case 60:
					goto _ctr142;case 61:
					goto _ctr143;case 62:
					goto _ctr144;case 63:
					goto _ctr145;case 64:
					goto _ctr146;case 65:
					goto _ctr147;case 66:
					goto _ctr148;case 67:
					goto _ctr149;case 68:
					goto _ctr150;case 69:
					goto _ctr151;case 70:
					goto _ctr152;case 71:
					goto _ctr153;case 72:
					goto _ctr154;case 73:
					goto _ctr155;case 74:
					goto _ctr156;case 75:
					goto _ctr157;case 76:
					goto _ctr158;case 77:
					goto _ctr159;case 78:
					goto _ctr160;case 79:
					goto _ctr161;case 80:
					goto _ctr162;	
				}
			}
			
		}
		if cs >= 81  {
			goto _out; 
		}
		_pop: {}
		_out: {}
	}
	if err != nil {
		return err
	}
	if p != eof {
		return errors.New("invalid nss")
	}
	_=pct
	return nil
}
