FROM sha256:99132805a8fba15728bd1f32feb2c326beff18ea30d82ad82cc7e9a7c04da356
ENV __doozer=update BUILD_RELEASE=202112132021.p0.g2a13a81.assembly.stream BUILD_VERSION=v4.6.0 OS_GIT_MAJOR=4 OS_GIT_MINOR=6 OS_GIT_PATCH=0 OS_GIT_TREE_STATE=clean OS_GIT_VERSION=4.6.0-202112132021.p0.g2a13a81.assembly.stream SOURCE_GIT_TREE_STATE=clean 
ENV __doozer=merge OS_GIT_COMMIT=2a13a81 OS_GIT_VERSION=4.6.0-202112132021.p0.g2a13a81.assembly.stream-2a13a81 SOURCE_DATE_EPOCH=1639424735 SOURCE_GIT_COMMIT=2a13a81f7fcbb01db50add1430a08e5ec4d38be6 SOURCE_GIT_TAG=v3.11.0-alpha.0-1010-g2a13a81f SOURCE_GIT_URL=https://github.com/openshift/origin-aggregated-logging 

MAINTAINER OpenShift Development <dev@lists.openshift.redhat.com>


EXPOSE 9200
EXPOSE 9300
USER 0

ARG ES_ARCHIVE_URL
ARG PROMETHEUS_EXPORTER_URL
ARG OPENDISTRO_URL
ARG OPENSHIFT_CI

ENV ES_PATH_CONF=/etc/elasticsearch/ \
    ES_HOME=/usr/share/elasticsearch \
    ES_VER=6.8.1.redhat-00012 \
    HOME=/opt/app-root/src \
    INSTANCE_RAM=512G \
    JAVA_VER=11 \
    JAVA_HOME=/usr/lib/jvm/jre \
    NODE_QUORUM=1 \
    PROMETHEUS_EXPORTER_VER=6.8.1.0 \
    OPENDISTRO_VER=0.10.1.2-redhat-00006 \
    PLUGIN_LOGLEVEL=INFO \
    RECOVER_AFTER_NODES=1 \
    RECOVER_EXPECTED_NODES=1 \
    RECOVER_AFTER_TIME=5m \
    DHE_TMP_KEY_SIZE=2048 \
    RELEASE_STREAM=prod \
    OPENSHIFT_CI=${OPENSHIFT_CI:-false}

ARG MAVEN_REPO_URL=${MAVEN_REPO_URL:-file:///artifacts/}

RUN packages="java-${JAVA_VER}-openjdk-headless \
              python36 python3-pyyaml  \
              hostname \
              openssl \
              zip \
              unzip" && \
    yum install -y --setopt=tsflags=nodocs ${packages} && \
    rpm -V ${packages} && \
    alternatives --set python /usr/bin/python3 && \
    yum clean all

ADD extra-jvm.options install-es.sh ci-env.sh /var/tmp

# Since artifacts does not exist during CI build, include README.MD
# which will prevent the copy from raising an error.
RUN mkdir /artifacts
# In an OSBS build, this will COPY artifacts from fetch-artifacts-koji.yaml. In a CI build, it will just
# copy the README.MD.
COPY artifacts/* /artifacts
COPY *.zip /
RUN /var/tmp/install-es.sh

ADD sgconfig/ ${HOME}/sgconfig/
ADD index_templates/ ${ES_HOME}/index_templates/
ADD index_patterns/ ${ES_HOME}/index_patterns/
ADD init/ ${ES_HOME}/init/
ADD probe/ ${ES_HOME}/probe/
ADD init.sh run.sh ci-env.sh install.sh ${HOME}/
COPY utils/** /usr/local/bin/

RUN ${HOME}/install.sh && rm -rf /artifacts

WORKDIR ${HOME}
USER 1000
CMD ["sh", "/opt/app-root/src/run.sh"]

LABEL \
        License="GPLv2+" \
        io.k8s.description="Elasticsearch container for EFK aggregated logging storage" \
        io.k8s.display-name="Elasticsearch 6" \
        io.openshift.tags="logging,elk,elasticsearch" \
        vendor="Red Hat" \
        name="openshift/ose-logging-elasticsearch6" \
        com.redhat.component="logging-elasticsearch6-container" \
        io.openshift.maintainer.product="OpenShift Container Platform" \
        io.openshift.maintainer.component="Logging" \
        release="202112132021.p0.g2a13a81.assembly.stream" \
        io.openshift.build.commit.id="2a13a81f7fcbb01db50add1430a08e5ec4d38be6" \
        io.openshift.build.source-location="https://github.com/openshift/origin-aggregated-logging" \
        io.openshift.build.commit.url="https://github.com/openshift/origin-aggregated-logging/commit/2a13a81f7fcbb01db50add1430a08e5ec4d38be6" \
        version="v4.6.0"


ADD logging-elasticsearch6-container-v4.6.0-202112132021.p0.g2a13a81.assembly.stream.json /root/buildinfo/content_manifests/logging-elasticsearch6-container-v4.6.0-202112132021.p0.g2a13a81.assembly.stream.json
LABEL "com.redhat.license_terms"="https://www.redhat.com/agreements" "distribution-scope"="public" "vendor"="Red Hat, Inc." "build-date"="2021-12-13T20:25:40.077527" "architecture"="x86_64" "vcs-type"="git" "vcs-ref"="aed8119d2cc4255488e2fc623dfbea9faa4e997c" "com.redhat.build-host"="cpt-1003.osbs.prod.upshift.rdu2.redhat.com" "description"="Elasticsearch container for EFK aggregated logging storage" "url"="https://access.redhat.com/containers/#/registry.access.redhat.com/openshift/ose-logging-elasticsearch6/images/v4.6.0-202112132021.p0.g2a13a81.assembly.stream"