// Code generated by ragel-go. DO NOT EDIT.

package httpreader

import (
	"errors"
	"strconv"
)

// The "go generate" command assumes ragel 7, which is shipped in Fedora.

//go:generate sh -e ragel.sh

// ContentRange is a parsed "bytes" content range.
//
// Unpopulated sections of the header are set to -1; refer to RFC7233 for
// more information.
type ContentRange struct {
	First, Last, Length int64
}

// Reset sets all fields to a known value (-1).
func (r *ContentRange) Reset() {
	r.First = -1
	r.Last = -1
	r.Length = -1
}

// Parse populates the receiver with the "bytes" content range from the
// supplied header value or reports an error.
func (r *ContentRange) Parse(data string) error {
	r.Reset()
	// Action setup:
	var err error
	sc := 0
	// State machine setup:
	cs, p, pe, eof := 0, 0, len(data), len(data)
	var _content_range_trans_keys = []byte{1, 0, 6, 6, 10, 10, 9, 9, 7, 7, 8, 8, 0, 0, 2, 5, 4, 4, 5, 5, 3, 5, 5, 5, 4, 5, 2, 5, 5, 5, 1, 0, 0}
	var _content_range_char_class = []int8{0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 3, 1, 4, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 6, 1, 1, 7, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 8, 9, 1, 1, 1, 1, 10, 0}
	var _content_range_index_offsets = []int8{0, 0, 1, 2, 3, 4, 5, 6, 10, 11, 12, 15, 16, 18, 22, 23, 0}
	var _content_range_indices = []int8{2, 3, 4, 5, 6, 7, 8, 0, 0, 9, 10, 11, 13, 0, 12, 15, 17, 16, 19, 0, 0, 11, 21, 0}
	var _content_range_index_defaults = []int8{0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}
	var _content_range_cond_targs = []int8{0, 1, 2, 3, 4, 5, 6, 7, 8, 10, 9, 14, 10, 11, 11, 12, 12, 13, 13, 15, 14, 14, 0}
	var _content_range_cond_actions = []int8{0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 2, 0, 1, 0, 3, 0, 0, 4, 0, 0}
	var _content_range_eof_trans = []int8{1, 2, 3, 4, 5, 6, 7, 8, 9, 11, 13, 15, 17, 19, 21, 20, 0}
	var content_range_start int = 1
	var _ = content_range_start
	var content_range_first_final int = 14
	var _ = content_range_first_final
	var content_range_error int = 0
	var _ = content_range_error
	var content_range_en_main int = 1
	var _ = content_range_en_main
	{
		cs = int(content_range_start)
	}
	{
		var _trans uint = 0
		var _keys int
		var _inds int
		var _ic int
	_resume:
		{
		}
		if p == pe && p != eof {
			goto _out
		}
		if p == eof {
			if _content_range_eof_trans[cs] > 0 {
				_trans = uint(_content_range_eof_trans[cs]) - 1
			}
		} else {
			_keys = int((cs << 1))

			_inds = int(_content_range_index_offsets[cs])

			if (data[p]) <= 121 && (data[p]) >= 32 {
				_ic = int(_content_range_char_class[int((data[p]))-32])
				if _ic <= int(_content_range_trans_keys[_keys+1]) && _ic >= int(_content_range_trans_keys[_keys]) {
					_trans = uint(_content_range_indices[_inds+int((_ic-int(_content_range_trans_keys[_keys])))])
				} else {
					_trans = uint(_content_range_index_defaults[cs])
				}
			} else {
				_trans = uint(_content_range_index_defaults[cs])
			}
		}
		cs = int(_content_range_cond_targs[_trans])
		if _content_range_cond_actions[_trans] != 0 {
			switch _content_range_cond_actions[_trans] {
			case 1:
				{
					sc = p
				}
			case 4:
				{
					r.Length, err = strconv.ParseInt(data[sc:p], 10, 64)
					if err != nil {
						{
							p += 1
							goto _out
						}
					}
				}
			case 2:
				{
					r.First, err = strconv.ParseInt(data[sc:p], 10, 64)
					if err != nil {
						{
							p += 1
							goto _out
						}
					}
				}
			case 3:
				{
					r.Last, err = strconv.ParseInt(data[sc:p], 10, 64)
					if err != nil {
						{
							p += 1
							goto _out
						}
					}
				}
			}
		}
		if p == eof {
			if cs >= 14 {
				goto _out
			}
		} else {
			if cs != 0 {
				p += 1
				goto _resume
			}
		}
	_out:
		{
		}
	}
	if cs >= content_range_start && cs < content_range_first_final {
		// Expect that err is populated
		return err
	}
	if p != pe {
		// Didn't consume the header.
		return errors.New("malformed header")
	}
	return nil
}
