#!/bin/sh
set -e
ragel-go -F1 -o tmp.go content_range.rl
trap 'rm tmp.go tmp.ri ||:' EXIT
{
	printf '// Code generated by ragel-go. DO NOT EDIT.\n\n'
	sed '/^[[:space:]]\+$/d' < tmp.go
} |
	gofmt -s > content_range.go
