// Code generated by "stringer -linecomment -type op"; DO NOT EDIT.

package pep440

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[opMatch-1]
	_ = x[opExclusion-2]
	_ = x[opLTE-3]
	_ = x[opGTE-4]
	_ = x[opLT-5]
	_ = x[opGT-6]
}

const _op_name = "==!=<=>=<>"

var _op_index = [...]uint8{0, 2, 4, 6, 8, 9, 10}

func (i op) String() string {
	i -= 1
	if i < 0 || i >= op(len(_op_index)-1) {
		return "op(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _op_name[_op_index[i]:_op_index[i+1]]
}
