// Code generated by internal/cmd/plugintool; DO NOT EDIT.

package libindex

import "errors"
import _ "unsafe" // Needed for linker tricks
import "github.com/quay/claircore/toolkit/registry"
import "github.com/quay/claircore/indexer"

//go:linkname github_com_quay_claircore_indexer_loaderDescription github.com/quay/claircore/indexer.loaderDescription
var github_com_quay_claircore_indexer_loaderDescription registry.Description[indexer.DynamicPlugin]

//go:linkname github_com_quay_claircore_whiteout_desc github.com/quay/claircore/whiteout.desc
var github_com_quay_claircore_whiteout_desc registry.Description[indexer.Resolver]

func init() {
	var errs []error
	if err := registry.Register(
		`urn:claircore:indexer:dynamicplugin:ecosystem`,
		&github_com_quay_claircore_indexer_loaderDescription,
	); err != nil {
		errs = append(errs, err)
	}
	if err := registry.Register(
		"urn:claircore:indexer:resolver:whiteout",
		&github_com_quay_claircore_whiteout_desc,
	); err != nil {
		errs = append(errs, err)
	}

	if len(errs) != 0 {
		panic(errors.Join(errs...))
	}
}
