// Code generated by "stringer -type Compressor -linecomment"; DO NOT EDIT.

package ovalutil

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[CompressionNone-0]
	_ = x[CompressionGzip-1]
	_ = x[CompressionBzip2-2]
}

const _Compressor_name = "nonegzipbzip2"

var _Compressor_index = [...]uint8{0, 4, 8, 13}

func (i Compressor) String() string {
	if i >= Compressor(len(_Compressor_index)-1) {
		return "Compressor(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Compressor_name[_Compressor_index[i]:_Compressor_index[i+1]]
}
