// Code generated by "stringer -type Attribute -linecomment"; DO NOT EDIT.

package cpe

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Part-0]
	_ = x[Vendor-1]
	_ = x[Product-2]
	_ = x[Version-3]
	_ = x[Update-4]
	_ = x[Edition-5]
	_ = x[Language-6]
	_ = x[SwEdition-7]
	_ = x[TargetSW-8]
	_ = x[TargetHW-9]
	_ = x[Other-10]
}

const _Attribute_name = "partvendorproductversionupdateeditionlanguagesw_editiontarget_swtarget_hwother"

var _Attribute_index = [...]uint8{0, 4, 10, 17, 24, 30, 37, 45, 55, 64, 73, 78}

func (i Attribute) String() string {
	if i < 0 || i >= Attribute(len(_Attribute_index)-1) {
		return "Attribute(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Attribute_name[_Attribute_index[i]:_Attribute_index[i+1]]
}
