// Code generated by "stringer -type=Qualitative"; DO NOT EDIT.

package cvss

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[None-1]
	_ = x[Low-2]
	_ = x[Medium-3]
	_ = x[High-4]
	_ = x[Critical-5]
}

const _Qualitative_name = "NoneLowMediumHighCritical"

var _Qualitative_index = [...]uint8{0, 4, 7, 13, 17, 25}

func (i Qualitative) String() string {
	i -= 1
	if i < 0 || i >= Qualitative(len(_Qualitative_index)-1) {
		return "Qualitative(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _Qualitative_name[_Qualitative_index[i]:_Qualitative_index[i+1]]
}
