// Code generated by "stringer -type=V4Metric,v4Valid -linecomment"; DO NOT EDIT.

package cvss

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[V4AttackVector-0]
	_ = x[V4AttackComplexity-1]
	_ = x[V4AttackRequirements-2]
	_ = x[V4PrivilegesRequired-3]
	_ = x[V4UserInteraction-4]
	_ = x[V4VulnerableSystemConfidentiality-5]
	_ = x[V4VulnerableSystemIntegrity-6]
	_ = x[V4VulnerableSystemAvailability-7]
	_ = x[V4SubsequentSystemConfidentiality-8]
	_ = x[V4SubsequentSystemIntegrity-9]
	_ = x[V4SubsequentSystemAvailability-10]
	_ = x[V4ExploitMaturity-11]
	_ = x[V4ConfidentialityRequirement-12]
	_ = x[V4IntegrityRequirement-13]
	_ = x[V4AvailabilityRequirement-14]
	_ = x[V4ModifiedAttackVector-15]
	_ = x[V4ModifiedAttackComplexity-16]
	_ = x[V4ModifiedAttackRequirements-17]
	_ = x[V4ModifiedPrivilegesRequired-18]
	_ = x[V4ModifiedUserInteraction-19]
	_ = x[V4ModifiedVulnerableSystemConfidentiality-20]
	_ = x[V4ModifiedVulnerableSystemIntegrity-21]
	_ = x[V4ModifiedVulnerableSystemAvailability-22]
	_ = x[V4ModifiedSubsequentSystemConfidentiality-23]
	_ = x[V4ModifiedSubsequentSystemIntegrity-24]
	_ = x[V4ModifiedSubsequentSystemAvailability-25]
	_ = x[V4Safety-26]
	_ = x[V4Automatable-27]
	_ = x[V4Recovery-28]
	_ = x[V4ValueDensity-29]
	_ = x[V4VulnerabilityResponseEffort-30]
	_ = x[V4ProviderUrgency-31]
}

const _V4Metric_name = "AVACATPRUIVCVIVASCSISAECRIRARMAVMACMATMPRMUIMVCMVIMVAMSCMSIMSASAURVREU"

var _V4Metric_index = [...]uint8{0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 23, 25, 27, 29, 32, 35, 38, 41, 44, 47, 50, 53, 56, 59, 62, 63, 65, 66, 67, 69, 70}

func (i V4Metric) String() string {
	if i < 0 || i >= V4Metric(len(_V4Metric_index)-1) {
		return "V4Metric(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _V4Metric_name[_V4Metric_index[i]:_V4Metric_index[i+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[v4AttackVectorValid-0]
	_ = x[v4AttackComplexityValid-1]
	_ = x[v4AttackRequirementsValid-2]
	_ = x[v4PrivilegesRequiredValid-3]
	_ = x[v4UserInteractionValid-4]
	_ = x[v4VulnerableSystemConfidentialityValid-5]
	_ = x[v4SubsequentSystemConfidentialityValid-6]
	_ = x[v4VulnerableSystemIntegrityValid-7]
	_ = x[v4SubsequentSystemIntegrityValid-8]
	_ = x[v4VulnerableSystemAvailabilityValid-9]
	_ = x[v4SubsequentSystemAvailabilityValid-10]
	_ = x[v4ExploitMaturityValid-11]
	_ = x[v4ConfidentialityRequirementValid-12]
	_ = x[v4IntegrityRequirementValid-13]
	_ = x[v4AvailabilityRequirementValid-14]
	_ = x[v4ModifiedAttackVectorValid-15]
	_ = x[v4ModifiedAttackComplexityValid-16]
	_ = x[v4ModifiedAttackRequirementsValid-17]
	_ = x[v4ModifiedPrivilegesRequiredValid-18]
	_ = x[v4ModifiedUserInteractionValid-19]
	_ = x[v4ModifiedVulnerableSystemConfidentialityValid-20]
	_ = x[v4ModifiedVulnerableSystemIntegrityValid-21]
	_ = x[v4ModifiedVulnerableSystemAvailabilityValid-22]
	_ = x[v4ModifiedSubsequentSystemConfidentialityValid-23]
	_ = x[v4ModifiedSubsequentSystemIntegrityValid-24]
	_ = x[v4ModifiedSubsequentSystemAvailabilityValid-25]
	_ = x[v4SafetyValid-26]
	_ = x[v4AutomatableValid-27]
	_ = x[v4RecoveryValid-28]
	_ = x[v4ValueDensityValid-29]
	_ = x[v4VulnerabilityResponseEffortValid-30]
	_ = x[v4ProviderUrgencyValid-31]
}

const _v4Valid_name = "NALPLHNPNLHNPAHLNHLNHLNHLNHLNHLNXAPUXHMLXHMLXHMLXNALPXLHXNPXNLHXNPAXHLNXHLNXHLNXHLNXSHLNXSHLNXPNXNYXAUIXDCXLMHXRedAmberGreenClear"

var _v4Valid_index = [...]uint8{0, 4, 6, 8, 11, 14, 17, 20, 23, 26, 29, 32, 36, 40, 44, 48, 53, 56, 59, 63, 67, 71, 75, 79, 83, 88, 93, 96, 99, 103, 106, 110, 129}

func (i v4Valid) String() string {
	if i < 0 || i >= v4Valid(len(_v4Valid_index)-1) {
		return "v4Valid(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _v4Valid_name[_v4Valid_index[i]:_v4Valid_index[i+1]]
}
