// Code generated by internal/cmd/revlookup. DO NOT EDIT.

package main

import "github.com/quay/claircore/toolkit/types/cvss"

var v4Rev = map[string]cvss.V4Metric{
	"AV":  0,
	"AC":  1,
	"AT":  2,
	"PR":  3,
	"UI":  4,
	"VC":  5,
	"VI":  6,
	"VA":  7,
	"SC":  8,
	"SI":  9,
	"SA":  10,
	"E":   11,
	"CR":  12,
	"IR":  13,
	"AR":  14,
	"MAV": 15,
	"MAC": 16,
	"MAT": 17,
	"MPR": 18,
	"MUI": 19,
	"MVC": 20,
	"MVI": 21,
	"MVA": 22,
	"MSC": 23,
	"MSI": 24,
	"MSA": 25,
	"S":   26,
	"AU":  27,
	"R":   28,
	"V":   29,
	"RE":  30,
	"U":   31,
}
