// Code generated by "stringer -type errorDurability -linecomment"; DO NOT EDIT.

package controller

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[errKindUnspecified-0]
	_ = x[errKindBlob-1]
	_ = x[errKindCode-2]
	_ = x[errKindTransient-3]
}

const _errorDurability_name = "unspecifiedblobcodetransient"

var _errorDurability_index = [...]uint8{0, 11, 15, 19, 28}

func (i errorDurability) String() string {
	if i >= errorDurability(len(_errorDurability_index)-1) {
		return "errorDurability(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _errorDurability_name[_errorDurability_index[i]:_errorDurability_index[i+1]]
}
