// Code generated by "stringer -type=componentKind -linecomment"; DO NOT EDIT.

package maven

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[kindNull-0]
	_ = x[kindInt-1]
	_ = x[kindString-2]
	_ = x[kindList-3]
}

const _componentKind_name = "nullintstringlist"

var _componentKind_index = [...]uint8{0, 4, 7, 13, 17}

func (i componentKind) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_componentKind_index)-1 {
		return "componentKind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _componentKind_name[_componentKind_index[idx]:_componentKind_index[idx+1]]
}
