// Code generated by "stringer -type cmp -linecomment -output cmp_string_test.go"; DO NOT EDIT.

package rpmver

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[cmpLT - -1]
	_ = x[cmpEQ-0]
	_ = x[cmpGT-1]
}

const _cmp_name = "<==>"

var _cmp_index = [...]uint8{0, 1, 3, 4}

func (i cmp) String() string {
	i -= -1
	if i < 0 || i >= cmp(len(_cmp_index)-1) {
		return "cmp(" + strconv.FormatInt(int64(i+-1), 10) + ")"
	}
	return _cmp_name[_cmp_index[i]:_cmp_index[i+1]]
}
