package rpm

type tagTab struct {
	Short      string
	Val        Tag
	Type       Kind
	ReturnType returnType
	Extension  bool
}

func (t tagTab) Name() string {
	return t.Val.String()
}

var tagTable = [...]tagTab{
	{"Headerimage", TagHeaderImage, TypeNull, returnAny, false},
	{"Headersignatures", TagHeaderSignatures, TypeNull, returnAny, false},
	{"Headerimmutable", TagHeaderImmutable, TypeNull, returnAny, false},
	{"Headerregions", TagHeaderRegions, TypeNull, returnAny, false},
	{"Headeri18ntable", TagHeaderI18nTable, TypeStringArray, returnArray, false},
	{"Sigsize", TagSigSize, TypeInt32, returnScalar, false},
	{"Sigpgp", TagSigPGP, TypeBin, returnScalar, false},
	{"Sigmd5", TagSigMD5, TypeBin, returnScalar, false},
	{"Siggpg", TagSigGPG, TypeBin, returnScalar, false},
	{"Pubkeys", TagPubKeys, TypeStringArray, returnArray, false},
	{"Dsaheader", TagDSAHeader, TypeBin, returnScalar, false},
	{"Rsaheader", TagRSAHeader, TypeBin, returnScalar, false},
	{"Sha1header", TagSHA1Header, TypeString, returnScalar, false},
	{"Longsigsize", TagLongSigSize, TypeInt64, returnScalar, false},
	{"Longarchivesize", TagLongArchiveSize, TypeInt64, returnScalar, false},
	{"Sha256header", TagSHA256Header, TypeString, returnScalar, false},
	{"Veritysignatures", TagVeritySignatures, TypeStringArray, returnArray, false},
	{"Veritysignaturealgo", TagVeritySignatureAlgo, TypeInt32, returnScalar, false},
	{"Name", TagName, TypeString, returnScalar, false},
	{"Version", TagVersion, TypeString, returnScalar, false},
	{"Release", TagRelease, TypeString, returnScalar, false},
	{"Epoch", TagEpoch, TypeInt32, returnScalar, false},
	{"Summary", TagSummary, TypeI18nString, returnScalar, false},
	{"Description", TagDescription, TypeI18nString, returnScalar, false},
	{"Buildtime", TagBuildTime, TypeInt32, returnScalar, false},
	{"Buildhost", TagBuildHost, TypeString, returnScalar, false},
	{"Installtime", TagInstallTime, TypeInt32, returnScalar, false},
	{"Size", TagSize, TypeInt32, returnScalar, false},
	{"Distribution", TagDistribution, TypeString, returnScalar, false},
	{"Vendor", TagVendor, TypeString, returnScalar, false},
	{"Gif", TagGIF, TypeBin, returnScalar, false},
	{"Xpm", TagXPM, TypeBin, returnScalar, false},
	{"License", TagLicense, TypeString, returnScalar, false},
	{"Packager", TagPackager, TypeString, returnScalar, false},
	{"Group", TagGroup, TypeI18nString, returnScalar, false},
	{"Source", TagSource, TypeStringArray, returnArray, false},
	{"Patch", TagPatch, TypeStringArray, returnArray, false},
	{"Url", TagURL, TypeString, returnScalar, false},
	{"Os", TagOS, TypeString, returnScalar, false},
	{"Arch", TagArch, TypeString, returnScalar, false},
	{"Prein", TagPreInstall, TypeString, returnScalar, false},
	{"Postin", TagPostInstall, TypeString, returnScalar, false},
	{"Preun", TagPreUninstall, TypeString, returnScalar, false},
	{"Postun", TagPostUninstall, TypeString, returnScalar, false},
	{"Oldfilenames", TagOldFilenames, TypeStringArray, returnArray, false},
	{"Filesizes", TagFileSizes, TypeInt32, returnArray, false},
	{"Filestates", TagFileStates, TypeChar, returnArray, false},
	{"Filemodes", TagFileModes, TypeInt16, returnArray, false},
	{"Filerdevs", TagFileRDevs, TypeInt16, returnArray, false},
	{"Filemtimes", TagFileMTimes, TypeInt32, returnArray, false},
	{"Filedigests", TagFileDigests, TypeStringArray, returnArray, false},
	{"Filelinktos", TagFileLinkTos, TypeStringArray, returnArray, false},
	{"Fileflags", TagFileFlags, TypeInt32, returnArray, false},
	{"Fileusername", TagFileUsername, TypeStringArray, returnArray, false},
	{"Filegroupname", TagFileGroupname, TypeStringArray, returnArray, false},
	{"Icon", TagIcon, TypeBin, returnScalar, false},
	{"Sourcerpm", TagSourceRPM, TypeString, returnScalar, false},
	{"Fileverifyflags", TagFileVerifyFlags, TypeInt32, returnArray, false},
	{"Archivesize", TagArchiveSize, TypeInt32, returnScalar, false},
	{"Providename", TagProvideName, TypeStringArray, returnArray, false},
	{"Requireflags", TagRequireFlags, TypeInt32, returnArray, false},
	{"Requirename", TagRequireName, TypeStringArray, returnArray, false},
	{"Requireversion", TagRequireVersion, TypeStringArray, returnArray, false},
	{"Nosource", TagNoSource, TypeInt32, returnArray, false},
	{"Nopatch", TagNoPatch, TypeInt32, returnArray, false},
	{"Conflictflags", TagConflictFlags, TypeInt32, returnArray, false},
	{"Conflictname", TagConflictName, TypeStringArray, returnArray, false},
	{"Conflictversion", TagConflictVersion, TypeStringArray, returnArray, false},
	{"Excludearch", TagExcludeArch, TypeStringArray, returnArray, false},
	{"Excludeos", TagExcludeOS, TypeStringArray, returnArray, false},
	{"Exclusivearch", TagExclusiveArch, TypeStringArray, returnArray, false},
	{"Exclusiveos", TagExclusiveOS, TypeStringArray, returnArray, false},
	{"Rpmversion", TagRPMVersion, TypeString, returnScalar, false},
	{"Triggerscripts", TagTriggerScripts, TypeStringArray, returnArray, false},
	{"Triggername", TagTriggerName, TypeStringArray, returnArray, false},
	{"Triggerversion", TagTriggerVersion, TypeStringArray, returnArray, false},
	{"Triggerflags", TagTriggerFlags, TypeInt32, returnArray, false},
	{"Triggerindex", TagTriggerIndex, TypeInt32, returnArray, false},
	{"Verifyscript", TagVerifyScript, TypeString, returnScalar, false},
	{"Changelogtime", TagChangelogTime, TypeInt32, returnArray, false},
	{"Changelogname", TagChangelogName, TypeStringArray, returnArray, false},
	{"Changelogtext", TagChangelogText, TypeStringArray, returnArray, false},
	{"Preinprog", TagPreInstallProg, TypeStringArray, returnArray, false},
	{"Postinprog", TagPostInstallProg, TypeStringArray, returnArray, false},
	{"Preunprog", TagPreUninstallProg, TypeStringArray, returnArray, false},
	{"Postunprog", TagPostUninstallProg, TypeStringArray, returnArray, false},
	{"Buildarchs", TagBuildArchs, TypeStringArray, returnArray, false},
	{"Obsoletename", TagObsoleteName, TypeStringArray, returnArray, false},
	{"Verifyscriptprog", TagVerifyScriptProg, TypeStringArray, returnArray, false},
	{"Triggerscriptprog", TagTriggerScriptProg, TypeStringArray, returnArray, false},
	{"Cookie", TagCookie, TypeString, returnScalar, false},
	{"Filedevices", TagFileDevices, TypeInt32, returnArray, false},
	{"Fileinodes", TagFileInodes, TypeInt32, returnArray, false},
	{"Filelangs", TagFileLangs, TypeStringArray, returnArray, false},
	{"Prefixes", TagPrefixes, TypeStringArray, returnArray, false},
	{"Instprefixes", TagInstallPrefixes, TypeStringArray, returnArray, false},
	{"Sourcepackage", TagSourcePackage, TypeInt32, returnScalar, false},
	{"Provideflags", TagProvideFlags, TypeInt32, returnArray, false},
	{"Provideversion", TagProvideVersion, TypeStringArray, returnArray, false},
	{"Obsoleteflags", TagObsoleteFlags, TypeInt32, returnArray, false},
	{"Obsoleteversion", TagObsoleteVersion, TypeStringArray, returnArray, false},
	{"Dirindexes", TagDirindexes, TypeInt32, returnArray, false},
	{"Basenames", TagBasenames, TypeStringArray, returnArray, false},
	{"Dirnames", TagDirnames, TypeStringArray, returnArray, false},
	{"Origdirindexes", TagOrigDirindexes, TypeInt32, returnArray, false},
	{"Origbasenames", TagOrigBasenames, TypeStringArray, returnArray, false},
	{"Origdirnames", TagOrigDirnames, TypeStringArray, returnArray, false},
	{"Optflags", TagOptFlags, TypeString, returnScalar, false},
	{"Disturl", TagDistURL, TypeString, returnScalar, false},
	{"Payloadformat", TagPayloadFormat, TypeString, returnScalar, false},
	{"Payloadcompressor", TagPayloadCompressor, TypeString, returnScalar, false},
	{"Payloadflags", TagPayloadFlags, TypeString, returnScalar, false},
	{"Installcolor", TagInstallColor, TypeInt32, returnScalar, false},
	{"Installtid", TagInstallTID, TypeInt32, returnScalar, false},
	{"Removetid", TagRemoveTID, TypeInt32, returnScalar, false},
	{"Platform", TagPlatform, TypeString, returnScalar, false},
	{"Patchesname", TagPatchesName, TypeStringArray, returnArray, false},
	{"Patchesflags", TagPatchesFlags, TypeInt32, returnArray, false},
	{"Patchesversion", TagPatchesVersion, TypeStringArray, returnArray, false},
	{"Filecolors", TagFileColors, TypeInt32, returnArray, false},
	{"Fileclass", TagFileClass, TypeInt32, returnArray, false},
	{"Classdict", TagClassDict, TypeStringArray, returnArray, false},
	{"Filedependsx", TagFileDependsX, TypeInt32, returnArray, false},
	{"Filedependsn", TagFileDependsN, TypeInt32, returnArray, false},
	{"Dependsdict", TagDependsDict, TypeInt32, returnArray, false},
	{"Sourcepkgid", TagSourcePkgID, TypeBin, returnScalar, false},
	{"Filecontexts", TagFileContexts, TypeStringArray, returnArray, false},
	{"Fscontexts", TagFSContexts, TypeStringArray, returnArray, true},
	{"Recontexts", TagREContexts, TypeStringArray, returnArray, true},
	{"Policies", TagPolicies, TypeStringArray, returnArray, false},
	{"Pretrans", TagPreTrans, TypeString, returnScalar, false},
	{"Posttrans", TagPostTrans, TypeString, returnScalar, false},
	{"Pretransprog", TagPreTransProg, TypeStringArray, returnArray, false},
	{"Posttransprog", TagPostTransProg, TypeStringArray, returnArray, false},
	{"Disttag", TagDistTag, TypeString, returnScalar, false},
	{"Oldsuggestsname", TagOldSuggestsName, TypeStringArray, returnArray, false},
	{"Oldsuggestsversion", TagOldSuggestsVersion, TypeStringArray, returnArray, false},
	{"Oldsuggestsflags", TagOldSuggestsFlags, TypeInt32, returnArray, false},
	{"Oldenhancesname", TagOldEnhancesName, TypeStringArray, returnArray, false},
	{"Oldenhancesversion", TagOldEnhancesVersion, TypeStringArray, returnArray, false},
	{"Oldenhancesflags", TagOldEnhancesFlags, TypeInt32, returnArray, false},
	{"Dbinstance", TagDbInstance, TypeInt32, returnScalar, true},
	{"Nvra", TagNVRA, TypeString, returnScalar, true},
	{"Filenames", TagFilenames, TypeStringArray, returnArray, true},
	{"Fileprovide", TagFileProvide, TypeStringArray, returnArray, true},
	{"Filerequire", TagFileRequire, TypeStringArray, returnArray, true},
	{"Triggerconds", TagTriggerConds, TypeStringArray, returnArray, true},
	{"Triggertype", TagTriggerType, TypeStringArray, returnArray, true},
	{"Origfilenames", TagOrigFileNames, TypeStringArray, returnArray, true},
	{"Longfilesizes", TagLongFileSizes, TypeInt64, returnArray, false},
	{"Longsize", TagLongSize, TypeInt64, returnScalar, false},
	{"Filecaps", TagFileCaps, TypeStringArray, returnArray, false},
	{"Filedigestalgo", TagFileDigestAlgo, TypeInt32, returnScalar, false},
	{"Bugurl", TagBugURL, TypeString, returnScalar, false},
	{"Evr", TagEVR, TypeString, returnScalar, true},
	{"Nvr", TagNVR, TypeString, returnScalar, true},
	{"Nevr", TagNEVR, TypeString, returnScalar, true},
	{"Nevra", TagNEVRA, TypeString, returnScalar, true},
	{"Headercolor", TagHeaderColor, TypeInt32, returnScalar, true},
	{"Verbose", TagVerbose, TypeInt32, returnScalar, true},
	{"Epochnum", TagEpochNum, TypeInt32, returnScalar, true},
	{"Preinflags", TagPreInstallFlags, TypeInt32, returnScalar, false},
	{"Postinflags", TagPostInstallFlags, TypeInt32, returnScalar, false},
	{"Preunflags", TagPreUninstallFlags, TypeInt32, returnScalar, false},
	{"Postunflags", TagPostUninstallFlags, TypeInt32, returnScalar, false},
	{"Pretransflags", TagPreTransFlags, TypeInt32, returnScalar, false},
	{"Posttransflags", TagPostTransFlags, TypeInt32, returnScalar, false},
	{"Verifyscriptflags", TagVerifyScriptFlags, TypeInt32, returnScalar, false},
	{"Triggerscriptflags", TagTriggerScriptFlags, TypeInt32, returnArray, false},
	{"Policynames", TagPolicyNames, TypeStringArray, returnArray, false},
	{"Policytypes", TagPolicyTypes, TypeStringArray, returnArray, false},
	{"Policytypesindexes", TagPolicyTypesIndexes, TypeInt32, returnArray, false},
	{"Policyflags", TagPolicyFlags, TypeInt32, returnArray, false},
	{"Vcs", TagVCS, TypeString, returnScalar, false},
	{"Ordername", TagOrderName, TypeStringArray, returnArray, false},
	{"Orderversion", TagOrderVersion, TypeStringArray, returnArray, false},
	{"Orderflags", TagOrderFlags, TypeInt32, returnArray, false},
	{"Instfilenames", TagInstFilenames, TypeStringArray, returnArray, true},
	{"Requirenevrs", TagRequireNEVRS, TypeStringArray, returnArray, true},
	{"Providenevrs", TagProvideNEVRS, TypeStringArray, returnArray, true},
	{"Obsoletenevrs", TagObsoleteNEVRS, TypeStringArray, returnArray, true},
	{"Conflictnevrs", TagConflictNEVRS, TypeStringArray, returnArray, true},
	{"Filenlinks", TagFileNLinks, TypeInt32, returnArray, true},
	{"Recommendname", TagRecommendName, TypeStringArray, returnArray, false},
	{"Recommendversion", TagRecommendVersion, TypeStringArray, returnArray, false},
	{"Recommendflags", TagRecommendFlags, TypeInt32, returnArray, false},
	{"Suggestname", TagSuggestName, TypeStringArray, returnArray, false},
	{"Suggestversion", TagSuggestVersion, TypeStringArray, returnArray, false},
	{"Suggestflags", TagSuggestFlags, TypeInt32, returnArray, false},
	{"Supplementname", TagSupplementName, TypeStringArray, returnArray, false},
	{"Supplementversion", TagSupplementVersion, TypeStringArray, returnArray, false},
	{"Supplementflags", TagSupplementFlags, TypeInt32, returnArray, false},
	{"Enhancename", TagEnhanceName, TypeStringArray, returnArray, false},
	{"Enhanceversion", TagEnhanceVersion, TypeStringArray, returnArray, false},
	{"Enhanceflags", TagEnhanceFlags, TypeInt32, returnArray, false},
	{"Recommendnevrs", TagRecommendNEVRS, TypeStringArray, returnArray, true},
	{"Suggestnevrs", TagSuggestNEVRS, TypeStringArray, returnArray, true},
	{"Supplementnevrs", TagSupplementNEVRS, TypeStringArray, returnArray, true},
	{"Enhancenevrs", TagEnhanceNEVRS, TypeStringArray, returnArray, true},
	{"Encoding", TagEncoding, TypeString, returnScalar, false},
	{"Filetriggerscripts", TagFileTriggerScripts, TypeStringArray, returnArray, false},
	{"Filetriggerscriptprog", TagFileTriggerScriptProg, TypeStringArray, returnArray, false},
	{"Filetriggerscriptflags", TagFileTriggerScriptFlags, TypeInt32, returnArray, false},
	{"Filetriggername", TagFileTriggerName, TypeStringArray, returnArray, false},
	{"Filetriggerindex", TagFileTriggerIndex, TypeInt32, returnArray, false},
	{"Filetriggerversion", TagFileTriggerVersion, TypeStringArray, returnArray, false},
	{"Filetriggerflags", TagFileTriggerFlags, TypeInt32, returnArray, false},
	{"Transfiletriggerscripts", TagTransFileTriggerScripts, TypeStringArray, returnArray, false},
	{"Transfiletriggerscriptprog", TagTransFileTriggerScriptProg, TypeStringArray, returnArray, false},
	{"Transfiletriggerscriptflags", TagTransFileTriggerScriptFlags, TypeInt32, returnArray, false},
	{"Transfiletriggername", TagTransFileTriggerName, TypeStringArray, returnArray, false},
	{"Transfiletriggerindex", TagTransFileTriggerIndex, TypeInt32, returnArray, false},
	{"Transfiletriggerversion", TagTransFileTriggerVersion, TypeStringArray, returnArray, false},
	{"Transfiletriggerflags", TagTransFileTriggerFlags, TypeInt32, returnArray, false},
	{"Filetriggerpriorities", TagFileTriggerPriorities, TypeInt32, returnArray, false},
	{"Transfiletriggerpriorities", TagTransFileTriggerPriorities, TypeInt32, returnArray, false},
	{"Filetriggerconds", TagFileTriggerConds, TypeStringArray, returnArray, true},
	{"Filetriggertype", TagFileTriggerType, TypeStringArray, returnArray, true},
	{"Transfiletriggerconds", TagTransFileTriggerConds, TypeStringArray, returnArray, true},
	{"Transfiletriggertype", TagTransFileTriggerType, TypeStringArray, returnArray, true},
	{"Filesignatures", TagFileSignatures, TypeStringArray, returnArray, false},
	{"Filesignaturelength", TagFileSignatureLength, TypeInt32, returnScalar, false},
	{"Payloaddigest", TagPayloadDigest, TypeStringArray, returnArray, false},
	{"Payloaddigestalgo", TagPayloadDigestAlgo, TypeInt32, returnScalar, false},
	{"Modularitylabel", TagModularityLabel, TypeString, returnScalar, false},
	{"Payloaddigestalt", TagPayloadDigestAlt, TypeStringArray, returnArray, false},
	{"Archsuffix", TagArchSuffix, TypeString, returnScalar, true},
}

var tagByValue map[Tag]int

func init() {
	tagByValue = make(map[Tag]int, len(tagTable))
	for i, t := range tagTable[:] {
		tagByValue[t.Val] = i
	}
}
