CREATE TABLE IF NOT EXISTS "@table" (version INTEGER PRIMARY KEY NOT NULL);

ALTER TABLE "@table"
ADD IF NOT EXISTS application_work_required BOOLEAN NOT NULL DEFAULT FALSE,
ADD IF NOT EXISTS created_at TIMESTAMPTZ NOT NULL DEFAULT transaction_timestamp(),
ADD IF NOT EXISTS finished_at TIMESTAMPTZ DEFAULT NULL;
