// Code generated by "stringer -type varExpand -linecomment"; DO NOT EDIT.

package dockerfile

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[varExpandSimple-0]
	_ = x[varExpandDefault-1]
	_ = x[varExpandDefaultNull-2]
	_ = x[varSetDefault-3]
	_ = x[varSetDefaultNull-4]
	_ = x[varExpandAlternate-5]
	_ = x[varExpandAlternateNull-6]
	_ = x[varErrIfUnset-7]
	_ = x[varErrIfUnsetNull-8]
	_ = x[varTrimSuffix-9]
	_ = x[varTrimSuffixGreedy-10]
	_ = x[varTrimPrefix-11]
	_ = x[varTrimPrefixGreedy-12]
}

const _varExpand_name = "simple expansiondefault expansiondefault+null expansionset defaultset default, incl. nullalternate expansionalternate expanxion, incl. nullerror if unseterror if unset or nulltrim suffixgreedy trim suffixtrim prefixgreedy trim prefix"

var _varExpand_index = [...]uint8{0, 16, 33, 55, 66, 89, 108, 139, 153, 175, 186, 204, 215, 233}

func (i varExpand) String() string {
	if i >= varExpand(len(_varExpand_index)-1) {
		return "varExpand(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _varExpand_name[_varExpand_index[i]:_varExpand_index[i+1]]
}
