// Code generated by "stringer -linecomment -type=PageType,HashPageType"; DO NOT EDIT.

package bdb

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[PageTypeInvalid-0]
	_ = x[PageTypeDuplicate-1]
	_ = x[PageTypeHashUnsorted-2]
	_ = x[PageTypeBtreeInternal-3]
	_ = x[PageTypeRecnoInternal-4]
	_ = x[PageTypeBtreeLeaf-5]
	_ = x[PageTypeRecnoLeaf-6]
	_ = x[PageTypeOverflow-7]
	_ = x[PageTypeHashMeta-8]
	_ = x[PageTypeBtreeMeta-9]
	_ = x[PageTypeQamMeta-10]
	_ = x[PageTypeQamData-11]
	_ = x[PageTypeDupLeaf-12]
	_ = x[PageTypeHash-13]
	_ = x[PageTypeHeapMeta-14]
	_ = x[PageTypeHeap-15]
	_ = x[PageTypeHeapInternal-16]
}

const _PageType_name = "P_INVALIDP_DUPLICATEP_HASH_UNSORTEDP_IBTREEP_IRECNOP_LBTREEP_LRECNOP_OVERFLOWP_HASHMETAP_BTREEMETAP_QAMMETAP_QAMDATAP_LDUPP_HASHP_HEAPMETAP_HEAPP_IHEAP"

var _PageType_index = [...]uint8{0, 9, 20, 35, 43, 51, 59, 67, 77, 87, 98, 107, 116, 122, 128, 138, 144, 151}

func (i PageType) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_PageType_index)-1 {
		return "PageType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _PageType_name[_PageType_index[idx]:_PageType_index[idx+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[HashPageTypeInvalid-0]
	_ = x[HashPageTypeKeyData-1]
	_ = x[HashPageTypeDuplicate-2]
	_ = x[HashPageTypeOffpage-3]
	_ = x[HashPageTypeOffDup-4]
	_ = x[HashPageTypeBlob-5]
}

const _HashPageType_name = "HashPageTypeInvalidHashPageTypeKeyDataHashPageTypeDuplicateHashPageTypeOffpageHashPageTypeOffDupHashPageTypeBlob"

var _HashPageType_index = [...]uint8{0, 19, 38, 59, 78, 96, 112}

func (i HashPageType) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_HashPageType_index)-1 {
		return "HashPageType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _HashPageType_name[_HashPageType_index[idx]:_HashPageType_index[idx+1]]
}
