// Code generated by "stringer -linecomment -type dbKind"; DO NOT EDIT.

package rpm

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[kindBDB-1]
	_ = x[kindSQLite-2]
	_ = x[kindNDB-3]
}

const _dbKind_name = "bdbsqlitendb"

var _dbKind_index = [...]uint8{0, 3, 9, 12}

func (i dbKind) String() string {
	i -= 1
	if i >= dbKind(len(_dbKind_index)-1) {
		return "dbKind(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _dbKind_name[_dbKind_index[i]:_dbKind_index[i+1]]
}
